const _SAVE_ROOT_PATH = Ref{String}(pwd())

"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end


"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            @info "Created save directory: $abs_path"
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        @info "Module save root path set to: $(_SAVE_ROOT_PATH[])"

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    @info "Created subdirectory: $subdir_path"
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



"""
Calculates the hash of a given params dictionary
"""
function calculateHash(params::ParamDict)
    sorted_keys = sort(collect(keys(params)))
    stringToHash = join(map(key -> "$key => $(params[key])", sorted_keys))
    return bytes2hex(sha256(stringToHash))
end
using Dates # Ensure this is imported

"""
Saves the given simulation mesh in the folder given by save_data.
Generates a filename based on Hash + Timestamp.

If a file with the exact same parameters already exists:
- Overwrites it if `overwrite=true`.
- Skips saving if `overwrite=false`.

If no matching parameters are found (even if the hash collides), a new file is created.
"""
function saveSimData(sim_data::AbstractSimData; overwrite::Bool = false)
    
    # 1. Check if this exact simulation already exists
    try
        existing_file = getFileName(sim_data.params)
        
        # --- CASE: File Exists ---
        if overwrite
            save(existing_file, "sim_data", sim_data)
            @warn "Existing simulation data overwritten at: $existing_file"
        else
            @info "Simulation data already exists at: $existing_file. Skipping save."
        end
        return # Exit, job done
    catch e
        if !isa(e, SimFileNotFoundError)
            rethrow(e)
        end
        # If SimFileNotFoundError, we proceed to save a new file
    end

    # --- CASE: New File Needed ---
    hash_val = calculateHash(sim_data.params)
    timestamp = Dates.format(now(), "yyyy-mm-dd_HH-MM-SS_sss") # Millisecond precision to be safe
    
    save_data = get_save_path() * "/data/"
    if !isdir(save_data); mkpath(save_data); end

    # Pattern: Hash_Timestamp.jld2
    file_name = joinpath(save_data, "$(hash_val)_$(timestamp).jld2")

    save(file_name, "sim_data", sim_data)
    @info "SimData saved to new file: $file_name"
end

function saveSimData(::NoSimData; kwargs...)
    return
end

"""
Returns the filename of the simulation data corresponding to the given params dictionary.
Searches all files matching the hash prefix to find the one with matching parameters.
Throws SimFileNotFoundError if no matching file is found.
"""
function getFileName(params::ParamDict)
    hash_val = calculateHash(params)
    save_data = get_save_path() * "/data/"
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    # Get all files in directory
    all_files = readdir(save_data)

    # Filter for files that start with the hash
    # Expecting format: HASH_TIMESTAMP.jld2
    candidate_files = filter(f -> startswith(f, hash_val) && endswith(f, ".jld2"), all_files)

    # Loop through candidates to check actual parameters
    for file in candidate_files
        full_path = joinpath(save_data, file)
        try
            # Load only the data needed to check parameters
            # Note: We load the whole object because JLD2 structure usually requires it 
            # to check nested params, unless you stored params separately.
            sim_data_saved = load(full_path, "sim_data")
            
            if params == sim_data_saved.params
                @debug "Found matching file: $full_path"
                return full_path
            end
        catch e
            @warn "Failed to load candidate file $file during search." exception=(e, catch_backtrace())
            # Continue searching other candidates
        end
    end

    # If loop finishes without returning
    throw(SimFileNotFoundError("Requested file with matching parameters does not exist (searched $(length(candidate_files)) candidates with hash $hash_val)."))
end

"""
Loads the simulation data corresponding to the given params dictionary as a simulation mesh
"""
function loadSimData(params::ParamDict)
    # getFileName does the heavy lifting of finding the correct timestamped file
    return load(getFileName(params))["sim_data"]
end

# Overload for loading directly by hash is tricky now because multiple files 
# might share the hash (collisions). This function assumes you want *any* file 
# with that hash, or strictly expects only one.
function loadSimData(hash_prefix::String)
    save_data = get_save_path() * "/data/"
    all_files = readdir(save_data)
    candidates = filter(f -> startswith(f, hash_prefix) && endswith(f, ".jld2"), all_files)
    
    if isempty(candidates)
         error("No files found with hash prefix: $hash_prefix")
    end

    # Sort by time (assuming standard naming) to get the latest? 
    # Or just pick the first one. Let's pick the latest.
    sort!(candidates) 
    file_name = joinpath(save_data, candidates[end])
    
    return load(file_name)["sim_data"]
end

"""
Loads only the stats field of the simulation mesh
"""
function getStats(params::ParamDict)
    sim_data = loadSimData(params)
    return sim_data.stats
end

"""
Checks if simulation data already exists for the given parameter dictionary.
Returns true if found, false only if specifically not found.
"""
function doesSimDataExist(params::ParamDict)
    try
        getFileName(params)
        return true
    catch e
        if isa(e, SimFileNotFoundError)
            return false
        else
            @error "Unexpected error during file existence check!" exception=(e, catch_backtrace())
            rethrow(e)
        end
    end
end

"""
Deletes all saved simulation meshes with the given keys and values in its parameter dictionary.
"""
function deleteSimData(keys::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    if !isdir(save_data); return; end
    
    files = readdir(save_data)
    for file in files
        if !endswith(file, ".jld2"); continue; end
        
        full_path = joinpath(save_data, file)
        try
            sim_data = load(full_path, "sim_data")
            deletion = true
            for (i,key) in enumerate(keys)
                # Check if key exists and matches value/type
                if !haskey(sim_data.params, key) || !(sim_data.params[key] == vals[i])
                    deletion = false
                    break
                end
            end
            
            if deletion
                @warn "Deleting file matching criteria: $file"
                rm(full_path)
            end
        catch e
            @warn "Could not load file $file for deletion check" exception=e
        end
    end
end

"""
Changes the paramseter dictionary of a simulation mesh from the old values to the new ones. Helpful if unused paramseters need to be changed or the type 
is wrong (e.g. Int instead of Float). Note that the values are not changed, hence use with caution.

"""
function changeparams(ks::Vector{String}, oldVals::Vector, newVals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                if sim_data.params[key] == oldVals[i]
                    sim_data.params[key] = newVals[i]
                    saveSimData(sim_data; overwrite = true)
                    @info "Changed simulation mesh is saved!"
                end
            end
        end
    end
end

"""
Returns all saved simulation meshes with the given parameters.
"""
function getAllSimData(ks::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    res = []
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        hit = true
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                hit = hit & (sim_data.params[key] == vals[i])
            else
                hit = false
            end
        end
        if hit
            push!(res, sim_data)
        end
    end
    return res
end

"""
Changes the given stat of all simulation meshes using the given function f. The function has to be of the
form f(u,x) or f(u,x,t) for the static and dynamic case respectively. It can also be used to add a new stat
to the simulation meshes.
"""
function changeStats(statsName::String, f::Function, simulation::String)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        if sim_data.params["simulation"] == simulation
            if simulation == "PDE"
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x, sim_data.t)
            else
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x)
            end
            saveSimData(sim_data; overwrite = true)
        end
    end    
end

"""
    get_julia_info()
Returns a dictionary containing the Julia version and the versions of 
loaded/project packages.
"""
function get_julia_info()
    info = Dict{String, Any}("Julia" => string(VERSION))
    
    # Get versions of all dependencies in the current project
    for (uuid, pkg) in Pkg.dependencies()
        if pkg.is_direct_dep
            info[pkg.name] = string(pkg.version)
        end
    end
    return info
end

"""
    _value_to_string_for_csv(v)

A robust helper to convert a Julia object to a string for CSV saving.
Explicitly strips type prefixes (like 'Any' or 'Vector{Float64}') from 
containers to ensure they are saved as clean, parsable Julia expressions.
"""
function _value_to_string_for_csv(v)
    # 1. Handle Symbols (Prepend colon so they parse back as Symbols)
    if isa(v, Symbol)
        return ":" * string(v)
    end

    # 2. Handle empty strings
    if v == ""
        return "<empty>"
    end

    # 3. Handle Arrays/Vectors (Strip type prefix: Any[...] -> [...])
    if isa(v, AbstractArray)
        s = string(v)
        # Replaces any alphanumeric + curly brace prefix before the first '['
        return replace(s, r"^[a-zA-Z0-9_{}, ]*\[" => "[")
    end
    
    # 4. Handle Tuples (Strip type prefix: NamedTuple(...) -> (...))
    if isa(v, Tuple)
        s = string(v)
        return replace(s, r"^[a-zA-Z0-9_{}, ]*\(" => "(")
    end

    # 5. Fallback for Numbers and basic Strings
    return string(v)
end

# This function can be added to your plotting_helpers.jl or a similar utility file.


"""
    get_git_info(start_path=".") -> Union{Dict{String, Any}, Nothing}

Inspects the Git repository containing the given path and returns key information
about the current state (HEAD commit). It robustly finds the repository root by
searching upwards from the `start_path`.
"""
function get_git_info(start_path::String = ".")
    try
        # --- Robust Repo Discovery Logic ---
        current_path = abspath(start_path)
        repo_root_path = nothing

        while true
            if isdir(joinpath(current_path, ".git"))
                repo_root_path = current_path
                break
            end
            parent_path = dirname(current_path)
            if parent_path == current_path; break; end
            current_path = parent_path
        end

        if isnothing(repo_root_path)
            @warn "Could not find a .git repository in or above the path: $(abspath(start_path))"
            return nothing
        end
        
        repo = LibGit2.GitRepo(repo_root_path)
        
        # --- Extract Information ---
        head_ref = LibGit2.head(repo)
        commit = LibGit2.peel(LibGit2.GitCommit, head_ref)
        
        # --- THIS IS THE FINAL FIX ---
        # The most robust, idiomatic way to get the hash is to construct a
        # `GitHash` object from the commit, then convert it to a string.
        commit_hash = string(LibGit2.GitHash(commit))
        # --- END OF FIX ---

        commit_summary = LibGit2.summary(commit)
        
        commit_count = try
            parse(Int, readchomp(`git -C $repo_root_path rev-list --count HEAD`))
        catch
            -1 # Indicate count could not be determined
        end

        return Dict{String, Any}(
            "git_commit_hash" => commit_hash,
            "git_commit_count" => commit_count,
            "git_commit_summary" => commit_summary,
            "julia_version" => string(VERSION)
        )
        
    catch e
        @warn "Could not retrieve Git information." exception=(e, catch_backtrace())
        return nothing
    end
end
function saveParametersToCSV(
    base_filename::String,
    save_dir::String,
    manager::PlotManager,
    metadata_general::Dict
)::Bool
    csv_filename = joinpath(save_dir, base_filename * ".csv")
    
    try
        cats, scopes, params, vals = String[], String[], String[], String[]

        function add_row(cat, scope, p, v)
            push!(cats, string(cat)); push!(scopes, string(scope))
            push!(params, string(p)); push!(vals, _value_to_string_for_csv(to_value(v)))
        end

        # --- 1. CATEGORY: Metadata ---
        # Scope: General (Timestamp, Save Type)
        for (k, v) in metadata_general; add_row("Metadata", "General", k, v); end
        
        # Scope: Git
        git_info = get_git_info(pwd()) # Uses your existing util
        if !isnothing(git_info)
            for (k, v) in git_info; add_row("Metadata", "Git", k, v); end
        end

        # Scope: Julia (Versions)
        julia_info = get_julia_info()
        for (k, v) in julia_info; add_row("Metadata", "Julia", k, v); end

        # --- NEW CATEGORY: Scene ---
        # Dynamically pulls all active UI widget states directly from controls
        for (key, obs) in manager.controls
            if endswith(key, "_Value")
                base_name = replace(key, "_Value" => "")
                add_row("Scene", "Slider", base_name, obs)
            elseif endswith(key, "_Selection")
                base_name = replace(key, "_Selection" => "")
                add_row("Scene", "Menu", base_name, obs)
            end
        end
        # --- 2. CATEGORY: Simulation ---
        # Shared params
        for (k, v) in manager.simulation["shared"]
            add_row("Simulation", "shared", k, v)
        end
        # Active method params
        for m_name in manager.methods[]
            if haskey(manager.simulation, m_name)
                for (k, v) in manager.simulation[m_name]
                    add_row("Simulation", m_name, k, v)
                end
            end
        end

        # --- 3. CATEGORY: UI ---
        for (scope, dict) in manager.ui
            for (k, v) in dict; add_row("UI", scope, k, v); end
        end
        # --- 4. CATEGORY: Config ---
        for (scope, dict) in manager.config
            for (k, v) in dict; add_row("Config", scope, k, v); end
        end

        CSV.write(csv_filename, DataFrame(Category=cats, Scope=scopes, Parameter=params, Value=vals))
        @info "Metadata and Parameters saved to $csv_filename"
        return true
    catch e
        @error "CSV Save Failed" exception=(e, catch_backtrace())
        return false
    end
end

"""
    capture_scene_metadata!(manager::PlotManager)

Iterates through all registered UI controls and saves their current values
into the metadata for the CSV export.
"""
function capture_scene_metadata!(manager::PlotManager)
    # We grab the to_value of every observable in controls
    return Dict(k => to_value(v) for (k, v) in manager.controls)
end


"""
    resolve_simulation_function(func_name_str::String, sim_func::Union{Function, Nothing}; target_module::Module = Main)

Resolves the simulation function. Evaluates the script in the `target_module` namespace 
(defaulting to `Main`) to avoid dependency bleed into the plotting package.
"""
function resolve_simulation_function(func_name_str::String, sim_func::Union{Function, Nothing}; target_module::Module = Main)
    if !isnothing(sim_func)
        return sim_func
    end

    try
        func_file = joinpath(_SAVE_ROOT_PATH[], "SimulationFunctions", func_name_str * ".jl")
        
        if isfile(func_file)
            @info "Dynamically loading function file into $target_module: $func_file"
            # Evaluate the file in the requested module scope
            Base.include(target_module, func_file)
        else
            @warn "File $func_file not found. Assuming function '$func_name_str' is already in $target_module scope."
        end
        
        # Fetch the compiled function directly from the requested module
        return getfield(target_module, Symbol(func_name_str))
        
    catch e
        @error "Failed to dynamically resolve simulation function." exception=(e, catch_backtrace())
        return nothing
    end
end

function SimulationConfig(sim_func::String, args...; target_module::Module = Main, kwargs...)
    f = resolve_simulation_function(sim_func, nothing; target_module = target_module)
    
    if isnothing(f)
        error("Aborting: Could not resolve simulation function '$sim_func' in module $target_module.")
    end
    
    SimulationConfig(f, args...; kwargs...)
end