"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end


"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            @info "Created save directory: $abs_path"
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        @info "Module save root path set to: $(_SAVE_ROOT_PATH[])"

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    @info "Created subdirectory: $subdir_path"
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



"""
Calculates the hash of a given params dictionary
"""
function calculateHash(params::ParamDict)
    sorted_keys = sort(collect(keys(params)))
    stringToHash = join(map(key -> "$key => $(params[key])", sorted_keys))
    return bytes2hex(sha256(stringToHash))
end

function saveSimData(sim_data::AbstractSimData; overwrite::Bool = false, suffix::String = "")
    try
        existing_file = getFileName(sim_data.params; suffix=suffix)
        if overwrite
            save(existing_file, "sim_data", sim_data)
            @warn "Existing simulation data overwritten at: $existing_file"
        else
            @info "Simulation data already exists at: $existing_file. Skipping save."
        end
        return
    catch e
        if !isa(e, SimFileNotFoundError)
            rethrow(e)
        end
    end

    hash_val = calculateHash(sim_data.params)
    timestamp = Dates.format(now(), "yyyy-mm-dd_HH-MM-SS_sss")
    
    save_data = joinpath(get_save_path(), "data")
    if !isdir(save_data); mkpath(save_data); end

    # Inject the suffix seamlessly
    suffix_str = isempty(suffix) ? "" : "_$(suffix)"
    file_name = joinpath(save_data, "$(hash_val)$(suffix_str)_$(timestamp).jld2")

    save(file_name, "sim_data", sim_data)
    @info "SimData saved to new file: $file_name"
end

function getFileName(params::ParamDict; suffix::String="")
    hash_val = calculateHash(params)
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)

    candidate_files = filter(all_files) do f
        !endswith(f, ".jld2") && return false
        
        if isempty(suffix)
            # Must match "HASH_" followed by a digit (the timestamp) to exclude "HASH_conv"
            return startswith(f, "$(hash_val)_") && occursin(r"^[0-9]", replace(f, "$(hash_val)_" => ""))
        else
            # Must match "HASH_conv_"
            return startswith(f, "$(hash_val)_$(suffix)_")
        end
    end

    for file in candidate_files
        full_path = joinpath(save_data, file)
        try
            sim_data_saved = load(full_path, "sim_data")
            if params == sim_data_saved.params
                return full_path
            end
        catch e
            @warn "Failed to load candidate file $file during search."
        end
    end

    throw(SimFileNotFoundError("File with matching parameters and suffix '$suffix' not found."))
end

function loadSimData(params::ParamDict; suffix::String="")
    return load(getFileName(params; suffix=suffix))["sim_data"]
end

function doesSimDataExist(params::ParamDict; suffix::String="")
    try
        getFileName(params; suffix=suffix)
        return true
    catch e
        if isa(e, SimFileNotFoundError)
             return false
        else
            rethrow(e)
        end
    end
end
# Overload for loading directly by hash is tricky now because multiple files 
# might share the hash (collisions). This function assumes you want *any* file 
# with that hash, or strictly expects only one.
function loadSimData(hash_prefix::String)
    save_data = get_save_path() * "/data/"
    all_files = readdir(save_data)
    candidates = filter(f -> startswith(f, hash_prefix) && endswith(f, ".jld2"), all_files)
    
    if isempty(candidates)
         error("No files found with hash prefix: $hash_prefix")
    end

    # Sort by time (assuming standard naming) to get the latest? 
    # Or just pick the first one. Let's pick the latest.
    sort!(candidates) 
    file_name = joinpath(save_data, candidates[end])
    
    return load(file_name)["sim_data"]
end

"""
Loads only the stats field of the simulation mesh
"""
function getStats(params::ParamDict)
    sim_data = loadSimData(params)
    return sim_data.stats
end

"""
Deletes all saved simulation meshes with the given keys and values in its parameter dictionary.
"""
function deleteSimData(keys::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    if !isdir(save_data); return; end
    
    files = readdir(save_data)
    for file in files
        if !endswith(file, ".jld2"); continue; end
        
        full_path = joinpath(save_data, file)
        try
            sim_data = load(full_path, "sim_data")
            deletion = true
            for (i,key) in enumerate(keys)
                # Check if key exists and matches value/type
                if !haskey(sim_data.params, key) || !(sim_data.params[key] == vals[i])
                    deletion = false
                    break
                end
            end
            
            if deletion
                @warn "Deleting file matching criteria: $file"
                rm(full_path)
            end
        catch e
            @warn "Could not load file $file for deletion check" exception=e
        end
    end
end

"""
Changes the paramseter dictionary of a simulation mesh from the old values to the new ones. Helpful if unused paramseters need to be changed or the type 
is wrong (e.g. Int instead of Float). Note that the values are not changed, hence use with caution.

"""
function changeparams(ks::Vector{String}, oldVals::Vector, newVals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                if sim_data.params[key] == oldVals[i]
                    sim_data.params[key] = newVals[i]
                    saveSimData(sim_data; overwrite = true)
                    @info "Changed simulation mesh is saved!"
                end
            end
        end
    end
end

"""
Returns all saved simulation meshes with the given parameters.
"""
function getAllSimData(ks::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    res = []
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        hit = true
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                hit = hit & (sim_data.params[key] == vals[i])
            else
                hit = false
            end
        end
        if hit
            push!(res, sim_data)
        end
    end
    return res
end

"""
Changes the given stat of all simulation meshes using the given function f. The function has to be of the
form f(u,x) or f(u,x,t) for the static and dynamic case respectively. It can also be used to add a new stat
to the simulation meshes.
"""
function changeStats(statsName::String, f::Function, simulation::String)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        if sim_data.params["simulation"] == simulation
            if simulation == "PDE"
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x, sim_data.t)
            else
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x)
            end
            saveSimData(sim_data; overwrite = true)
        end
    end    
end
