"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end
# Normalize scalar Ints or Tuples into a standard spatial Tuple
function _normalize_spatial_res(N_grid::Union{Int, Tuple}, DS::Int)
    if N_grid isa Int
        return ntuple(_ -> N_grid, Val(DS))
    elseif N_grid isa Tuple
        length(N_grid) == DS || error("Spatial grid tuple length $(length(N_grid)) does not match DS = $DS")
        return N_grid
    else
        error("Unsupported grid resolution type: $(typeof(N_grid))")
    end
end

# Generate standard string key from a spacetime resolution tuple
function get_conv_key(res::Tuple)
    return "conv_E_" * join(res, "x")
end

"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            @info "Created save directory: $abs_path"
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        @info "Module save root path set to: $(_SAVE_ROOT_PATH[])"

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    @info "Created subdirectory: $subdir_path"
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



# Normalizes values to a consistent string format before hashing
function _normalize_for_hash(val)
    if val isa Number
        # Coerce all numbers to Float64 so 1 and 1.0 become identical strings
        # Use a formatted string to avoid floating-point display quirks
        return string(Float64(val)) 
    elseif val isa Tuple || val isa AbstractArray
        # Recursively normalize collections
        return "[" * join([_normalize_for_hash(v) for v in val], ",") * "]"
    elseif val isa Symbol || val isa String
        return string(val)
    else
        # Fallback for complex custom types
        return string(val) 
    end
end

function calculate_hash(params::ParamDict)
    sorted_keys = sort(collect(keys(params)))
    # Apply the normalizer to ensure type-agnostic hashing
    stringToHash = join(map(key -> "$key => $(_normalize_for_hash(params[key]))", sorted_keys))
    return bytes2hex(sha256(stringToHash))
end

function get_file_name(params::ParamDict)
    hash_val = calculate_hash(params)
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)
    candidate_files = filter(f -> (endswith(f, "_$(hash_val).jld2") || startswith(f, "$(hash_val)_")) && endswith(f, ".jld2"), all_files)

    if isempty(candidate_files)
        throw(SimFileNotFoundError("File with matching parameters not found."))
    end

    sort!(candidate_files, by = f -> mtime(joinpath(save_data, f)), rev=true)
    
    # --- THE FIX: Exact Parameter Match Resolution ---
    for file in candidate_files
        full_path = joinpath(save_data, file)
        try
            is_match = jldopen(full_path, "r") do f
                # Grab the first available key to inspect its parameters
                if !isempty(keys(f))
                    first_key = first(keys(f))
                    saved_params = f[first_key].params
                    return saved_params == params
                end
                return false
            end
            
            if is_match
                return full_path
            end
        catch e
            @warn "Could not read $file during hash collision check." exception=e
            continue
        end
    end

    throw(SimFileNotFoundError("Hash matched, but exact parameters did not match any file."))
end

function save_sim_data(sim_data::AbstractSimData; overwrite::Bool = false)
    file_name = ""
    try
        file_name = get_file_name(sim_data.params)
    catch e
        if !isa(e, SimFileNotFoundError); rethrow(e); end
    end

    # 1. New File Initialization
    if isempty(file_name)
        hash_val = calculate_hash(sim_data.params)
        timestamp = Dates.format(now(), "yyyy-mm-dd_HH-MM-SS_sss")
        save_data = joinpath(get_save_path(), "data")
        if !isdir(save_data); mkpath(save_data); end
        
        file_name = joinpath(save_data, "$(timestamp)_$(hash_val).jld2")
        mode = "w"
        target_key = "raw"
    else
        mode = "a+"
        
        # 2. Determine Key based on Base Type mapping
        # Inside save_sim_data, replace the target_key block with this:
        target_key = jldopen(file_name, "r") do file
            if haskey(file, "raw")
                raw_data = file["raw"]
                
                if sim_data isa ESimData
                    # If raw is Eulerian and the sizes match exactly, we are overwriting raw
                    if raw_data isa ESimData && size(raw_data.u) == size(sim_data.u)
                        return "raw"
                    else
                        # Otherwise, this is either L->E or an E->E resampling!
                        return get_conv_key(size(sim_data.u))
                    end
                elseif sim_data isa LSimData
                    if raw_data isa LSimData
                        return "raw"
                    else
                        return "conv_L" # E -> L conversion
                    end
                end
            end
            return "raw" # Fallback if file exists but is empty
        end
    end

    # 3. Save the Data
    jldopen(file_name, mode) do file
        if haskey(file, target_key)
            if overwrite
                delete!(file, target_key)
                file[target_key] = sim_data
                @info "Overwrote existing '$target_key' in $(basename(file_name))"
                
            else
                @debug "'$target_key' already exists in $(basename(file_name)). Skipping save."
            end
        else
            file[target_key] = sim_data
            @info "Saved '$target_key' to $(basename(file_name))"
        end
        
        # --- Save native metadata instantly ---
        if target_key == "raw"
            native_str = sim_data isa ESimData ? :eulerian : :lagrangian
            if haskey(file, "native")
                delete!(file, "native")
            end
            file["native"] = native_str
        end
    end
end

# Default fallback routes to :raw
load_sim_data(params::ParamDict) = load_sim_data(params, Val(:raw))

# --- Fast Metadata Reader ---
function _get_native_type(file_name::String)
    return jldopen(file_name, "r") do file
        return file["native"]
    end
end

# ==============================================================================
# --- LOAD ROUTERS ---
# ==============================================================================

function load_sim_data(params::ParamDict, ::Val{:raw})
    file_name = get_file_name(params)
    return jldopen(file_name, "r") do file
        haskey(file, "raw") ? file["raw"] : throw(SimFileNotFoundError("Key 'raw' not found."))
    end
end

"""
    list_available_conversions(params::ParamDict)

Returns a list of all conversion key strings currently stored inside the JLD2 file.
"""
function list_available_conversions(params::ParamDict)
    file_name = get_file_name(params)
    return jldopen(file_name, "r") do file
        return filter(k -> startswith(k, "conv_"), keys(file))
    end
end

function load_sim_data(params::ParamDict, ::Val{:eulerian}, res::Tuple)
    file_name = get_file_name(params)
    
    # 1. Check if the raw data is ALREADY the perfect Eulerian grid we need
    is_perfect_match = jldopen(file_name, "r") do file
        raw = file["raw"]
        return raw isa ESimData && size(raw.u) == res
    end
    
    if is_perfect_match
        return load_sim_data(params, Val(:raw))
    end
    
    # 2. Check for an existing cached conversion matching this exact resolution
    key = get_conv_key(res)
    has_conv = jldopen(file_name, "r") do file; haskey(file, key); end
    
    if has_conv
        return jldopen(file_name, "r") do file; file[key]; end
    end
    
    # 3. Generate it on the fly
    @info "Target Eulerian resolution $key not found. Generating on the fly..."
    raw_data = load_sim_data(params, Val(:raw))
    
    conv_data = if raw_data isa LSimData
        convert_to_eulerian(raw_data, res)
    else
        resample_eulerian(raw_data, res)
    end
    
    save_sim_data(conv_data; overwrite=true) 
    return conv_data
end

function load_sim_data(params::ParamDict, ::Val{:lagrangian})
    native = _get_native_type(get_file_name(params))
    
    if native == :lagrangian
        return load_sim_data(params, Val(:raw))
    else
        # Directly load the L-conversion or generate it
        file_name = get_file_name(params)
        has_conv = jldopen(file_name, "r") do file; haskey(file, "conv_L"); end
        
        if has_conv
            return jldopen(file_name, "r") do file; file["conv_L"]; end
        else
            @info "Lagrangian conversion not found. Generating on the fly..."
            raw_data = load_sim_data(params, Val(:raw))
            conv_data = convert_to_lagrangian(raw_data)
            save_sim_data(conv_data; overwrite=true)
            return conv_data
        end
    end
end

# ==============================================================================
# --- EXISTENCE CHECKERS ---
# ==============================================================================

does_sim_data_exist(params::ParamDict) = does_sim_data_exist(params, Val(:raw))

function does_sim_data_exist(params::ParamDict, ::Val{:raw})
    try
        return jldopen(get_file_name(params), "r") do file; haskey(file, "raw"); end
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function does_sim_data_exist(params::ParamDict, ::Val{:eulerian}, res::Tuple)
    try
        file_name = get_file_name(params)
        native = _get_native_type(file_name)
        
        if native == :eulerian
            # If native is Eulerian, check if the raw data perfectly matches the requested resolution
            is_perfect_match = jldopen(file_name, "r") do file
                raw = file["raw"]
                return size(raw.u) == res
            end
            
            if is_perfect_match
                return true
            end
        end
        
        # If not a perfect raw match (or native is Lagrangian), check for the explicit cached key
        target_key = get_conv_key(res)
        return jldopen(file_name, "r") do file; haskey(file, target_key); end
        
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function does_sim_data_exist(params::ParamDict, ::Val{:lagrangian})
    try
        file_name = get_file_name(params)
        native = _get_native_type(file_name)
        
        if native == :lagrangian
            # If native is Lagrangian, we just need the raw data
            return jldopen(file_name, "r") do file; haskey(file, "raw"); end
        else
            # If native is Eulerian, check for the specific L-conversion key
            return jldopen(file_name, "r") do file; haskey(file, "conv_L"); end
        end
        
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function load_sim_data(hash_prefix::String; index::Int=1)
    clean_prefix = replace(hash_prefix, ".jld2" => "")
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)
    candidates = filter(f -> occursin(clean_prefix, f) && endswith(f, ".jld2"), all_files)
    
    if isempty(candidates)
         throw(SimFileNotFoundError("No files found matching the hash prefix: $clean_prefix"))
    end

    sort!(candidates, by = f -> mtime(joinpath(save_data, f)), rev=true)
    
    if index > length(candidates) || index < 1
        error("Requested index $index, but only $(length(candidates)) files match the hash '$clean_prefix'.")
    end

    file_name = joinpath(save_data, candidates[index])
    @info "Manual Load: Found $(length(candidates)) matching files. Loading index $index: $(candidates[index])"
    
    # Pure passthrough load to the primary raw data
    return JLD2.load(file_name)
end

"""
    check_data(data::AbstractSimData)

Generates a fast, allocation-free DataFrame summarizing the Min, Max, Mean, 
and NaN count for every component at every timestep. Works natively on both 
ESimData and LSimData.
"""
function check_data(data::AbstractSimData)
    T_len = length(data.t)
    
    # Dynamically determine the number of components (M)
    M = if data isa ESimData
        size(data.u, 1)
    else
        # For Lagrangian, peek at the first valid particle of the first timestep
        length(data.u) > 0 && length(data.u[1]) > 0 ? length(data.u[1][1]) : 1
    end
    
    # Preallocate the dictionary to build the DataFrame
    df_dict = Dict{Symbol, Vector{Float64}}()
    df_dict[:Time] = data.t
    
    for c in 1:M
        df_dict[Symbol("C$(c)_Min")]  = zeros(T_len)
        df_dict[Symbol("C$(c)_Max")]  = zeros(T_len)
        df_dict[Symbol("C$(c)_Mean")] = zeros(T_len)
        df_dict[Symbol("C$(c)_NaNs")] = zeros(T_len)
    end
    
    for m in 1:T_len
        for c in 1:M
            # Fast, allocation-free accumulators
            min_v, max_v = Inf, -Inf
            sum_v = 0.0
            valid_count, nan_count = 0, 0
            
            # 1. Extract the data iterator based on the struct type
            iterator = if data isa ESimData
                # Slice: [Component, X, Y, Z..., Time] -> extract specific component & time
                selectdim(selectdim(data.u, ndims(data.u), m), 1, c)
            else
                # Map lazily over the particles at this timestep
                (p[c] for p in data.u[m])
            end
            
            # 2. Single-pass evaluation (Zero memory allocations!)
            for val in iterator
                if isnan(val)
                    nan_count += 1
                else
                    min_v = min(min_v, val)
                    max_v = max(max_v, val)
                    sum_v += val
                    valid_count += 1
                end
            end
            
            # 3. Save to our DataFrame dictionary
            df_dict[Symbol("C$(c)_NaNs")][m] = nan_count
            
            if valid_count > 0
                df_dict[Symbol("C$(c)_Min")][m]  = min_v
                df_dict[Symbol("C$(c)_Max")][m]  = max_v
                df_dict[Symbol("C$(c)_Mean")][m] = sum_v / valid_count
            else
                df_dict[Symbol("C$(c)_Min")][m]  = NaN
                df_dict[Symbol("C$(c)_Max")][m]  = NaN
                df_dict[Symbol("C$(c)_Mean")][m] = NaN
            end
        end
    end
    
    # Construct the DataFrame and force the 'Time' column to be first
    df = DataFrame(df_dict)
    select!(df, :Time, Not(:Time))
    
    return df
end


"""
Deletes all saved simulation meshes with the given keys and values in its parameter dictionary.
"""
function delete_sim_data(keys::Vector{Symbol}, vals::Vector)
    save_data = get_save_path() * "/data/"
    if !isdir(save_data); return; end
    
    files = readdir(save_data)
    for file in files
        if !endswith(file, ".jld2"); continue; end
        
        full_path = joinpath(save_data, file)
        try
            sim_data = load(full_path, "raw")
            deletion = true
            for (i,key) in enumerate(keys)
                # Now safely comparing against a strictly typed ParamDict
                if !haskey(sim_data.params, key) || !(sim_data.params[key] == vals[i])
                    deletion = false
                    break
                end
            end
            
            if deletion
                @warn "Deleting file matching criteria: $file"
                rm(full_path)
            end
        catch e
            @warn "Could not load file $file for deletion check" exception=e
        end
    end
end

