const _ENABLE_CONV_CACHE = Ref{Bool}(false)

"""
    enable_cache!(val::Bool)

Toggles whether on-the-fly Eulerian and Lagrangian conversions are saved to disk.
"""
enable_cache!(val::Bool) = (_ENABLE_CONV_CACHE[] = val)

"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end
# Normalize scalar Ints or Tuples into a standard spatial Tuple
function _normalize_spatial_res(N_grid::Union{Int, Tuple}, DS::Int)
    if N_grid isa Int
        return ntuple(_ -> N_grid, Val(DS))
    elseif N_grid isa Tuple
        length(N_grid) == DS || error("Spatial grid tuple length $(length(N_grid)) does not match DS = $DS")
        return N_grid
    else
        error("Unsupported grid resolution type: $(typeof(N_grid))")
    end
end

# Generate standard string key from a spacetime resolution tuple
function get_conv_key(res::Tuple)
    return "conv_E_" * join(res, "x")
end

# ==============================================================================
# --- UNIFIED SERIALIZATION & PARSING ---
# ==============================================================================

"""
    val2str(v; top_level::Bool=true)

Recursively converts Julia objects into valid, evaluatable Julia code strings.
Uses `top_level` to keep CSV formatting clean for standalone strings, while 
applying strict `repr()` quoting to elements inside containers for type stability.
"""
function val2str(v; top_level::Bool=true)
    if v == ""
        return "<empty>"
    elseif isa(v, Function)
        return "Closure"
    elseif isa(v, Val)
        return string(v)
    elseif isa(v, Symbol) 
        return repr(v)
    elseif isa(v, AbstractString)
        # THE FIX: Drop the explicit quotes for top-level strings so the CSV writes them cleanly!
        return top_level ? String(v) : repr(v)
    elseif isa(v, Number) || isa(v, Type)
        return string(v)
    elseif isa(v, AbstractArray)
        T = eltype(v)
        prefix = T === Any ? "Any" : string(T)
        # Pass top_level=false so inner strings get their protective quotes back
        elements = join([val2str(x; top_level=false) for x in v], ", ")
        return "$(prefix)[$elements]"
    elseif isa(v, Tuple)
        elements = join([val2str(x; top_level=false) for x in v], ", ")
        return length(v) == 1 ? "($elements,)" : "($elements)"
    elseif isa(v, Dict)
        K, V = keytype(v), valtype(v)
        sorted_keys = sort(collect(keys(v)), by=string)
        elements = join(["$(val2str(k; top_level=false)) => $(val2str(v[k]; top_level=false))" for k in sorted_keys], ", ")
        return "Dict{$K, $V}($elements)"
    else
        T = typeof(v)
        type_name = string(T.name.name) 
        fields = propertynames(v)
        if isempty(fields)
            return type_name
        else
            field_strs = ["$f=$(val2str(getproperty(v, f); top_level=false))" for f in fields]
            return "$type_name(" * join(field_strs, ", ") * ")"
        end
    end
end


"""
    str2val(val_str::AbstractString)

Attempts to evaluate a string back into its native Julia type.
Falls back to a plain string if it represents a custom struct or unquoted UI input.
"""
function str2val(val_str::AbstractString)
    val_str = strip(val_str)
    if val_str == "<empty>" || isempty(val_str)
        return ""
    end
    
    try
        # Safely evaluates nicely formatted code: Symbol[:RK2], Dict{Int, Float64}(...), true, 42.0
        return eval(Meta.parse(val_str))
    catch e
        # Fallback for custom structs (GeometricDomain(...)) or raw unquoted UI strings
        return replace(val_str, r"^\"|\"$" => "")
    end
end

"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            @info "Created save directory: $abs_path"
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        @info "Module save root path set to: $(_SAVE_ROOT_PATH[])"

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    @info "Created subdirectory: $subdir_path"
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end

function calculate_hash(params::ParamDict)
    sorted_keys = sort(collect(keys(params)), by=string)
    # Feed val2str directly into the hashing engine for a bulletproof signature
    stringToHash = join(["$k => $(val2str(params[k]))" for k in sorted_keys], ", ")
    return bytes2hex(sha256(stringToHash))
end
# ==============================================================================
# --- IOUtils.jl Updates ---
# ==============================================================================

function get_file_name(params::ParamDict)
    hash_val = calculate_hash(params)
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)
    candidate_files = filter(f -> (endswith(f, "_$(hash_val).jld2") || startswith(f, "$(hash_val)_")) && endswith(f, ".jld2"), all_files)

    if isempty(candidate_files)
        throw(SimFileNotFoundError("File with matching parameters not found."))
    end

    # Return the most recent file matching the exact cryptographic hash
    sort!(candidate_files, by = f -> mtime(joinpath(save_data, f)), rev=true)
    
    # Cryptographic guarantee: if the SHA-256 hash matches, we do not need 
    # to load the file into RAM to verify structural equality.
    return joinpath(save_data, candidate_files[1])
end

function save_sim_data(sim_data::AbstractSimData; overwrite::Bool = false)
    # THE FIX: Condense the parameters into a human-readable, closure-free format!
    # This prevents JLD2 serialization warnings and massively shrinks the file size.
    condensed_params = Dict{Symbol, Any}()
    for (k, v) in sim_data.params
        condensed_params[k] = str2val(val2str(v))
    end
    
    # Mutate the sim_data's params in place so the heavy objects are stripped out 
    # before JLD2 attempts to save the 'raw' object to disk.
    empty!(sim_data.params)
    merge!(sim_data.params, condensed_params)

    file_name = ""
    try
        # The hash calculation remains 100% identical because the normalizer is idempotent!
        file_name = get_file_name(sim_data.params)
    catch e
        if !isa(e, SimFileNotFoundError); rethrow(e); end
    end

    if isempty(file_name)
        hash_val = calculate_hash(sim_data.params)
        timestamp = Dates.format(now(), "yyyy-mm-dd_HH-MM-SS_sss")
        save_data = joinpath(get_save_path(), "data")
        if !isdir(save_data); mkpath(save_data); end
        
        file_name = joinpath(save_data, "$(timestamp)_$(hash_val).jld2")
        
        jldopen(file_name, "w") do file
            file["raw"] = sim_data
            
            # --- WRITE FAST METADATA ---
            file["native"] = sim_data isa ESimData ? :eulerian : :lagrangian
            file["params"] = sim_data.params # Will now save the clean, stringified dictionary!
            file["stat_keys"] = collect(keys(sim_data.stats))
        end
        @info "Saved 'raw' to $(basename(file_name))"
    else
        jldopen(file_name, "a+") do file
            if haskey(file, "raw")
                if overwrite
                    delete!(file, "raw")
                    file["raw"] = sim_data
                    
                    # --- OVERWRITE FAST METADATA ---
                    if haskey(file, "params"); delete!(file, "params"); end
                    file["params"] = sim_data.params
                    
                    if haskey(file, "stat_keys"); delete!(file, "stat_keys"); end
                    file["stat_keys"] = collect(keys(sim_data.stats))
                    
                    if haskey(file, "native"); delete!(file, "native"); end
                    file["native"] = sim_data isa ESimData ? :eulerian : :lagrangian
                    
                    # Ruthlessly clear all stale conversion caches!
                    for k in keys(file)
                        if startswith(k, "conv_")
                            delete!(file, k)
                            @debug "Cleared outdated conversion cache: '$k'"
                        end
                    end
                    
                    @info "Overwrote existing 'raw' in $(basename(file_name)) and cleared all caches."
                else
                    @debug "'raw' already exists. Skipping save."
                end
            else
                file["raw"] = sim_data
                file["native"] = sim_data isa ESimData ? :eulerian : :lagrangian
                file["params"] = sim_data.params
                file["stat_keys"] = collect(keys(sim_data.stats))
                @info "Saved 'raw' to $(basename(file_name))"
            end
        end
    end
end

# Default fallback routes to :raw
load_sim_data(params::ParamDict) = load_sim_data(params, Val(:raw))

# --- Fast Metadata Reader ---
function _get_native_type(file_name::String)
    return jldopen(file_name, "r") do file
        return file["native"]
    end
end

# ==============================================================================
# --- LOAD ROUTERS ---
# ==============================================================================

function load_sim_data(params::ParamDict, ::Val{:raw})
    file_name = get_file_name(params)
    return jldopen(file_name, "r") do file
        haskey(file, "raw") ? file["raw"] : throw(SimFileNotFoundError("Key 'raw' not found."))
    end
end

"""
    list_available_conversions(params::ParamDict)

Returns a list of all conversion key strings currently stored inside the JLD2 file.
"""
function list_available_conversions(params::ParamDict)
    file_name = get_file_name(params)
    return jldopen(file_name, "r") do file
        return filter(k -> startswith(k, "conv_"), keys(file))
    end
end

function load_sim_data(params::ParamDict, ::Val{:eulerian}, res::Tuple)
    file_name = get_file_name(params)
    
    # 1. Check if the raw data is ALREADY the perfect Eulerian grid we need
    is_perfect_match = jldopen(file_name, "r") do file
        raw = file["raw"]
        return raw isa ESimData && size(raw.u) == res
    end
    
    if is_perfect_match
        return load_sim_data(params, Val(:raw))
    end
    
    # 2. Check for an existing cached conversion matching this exact resolution
    key = get_conv_key(res)
    has_conv = jldopen(file_name, "r") do file; haskey(file, key); end
    
    if has_conv
        return jldopen(file_name, "r") do file; file[key]; end
    end
    
    # 3. Generate it on the fly
    @info "Target Eulerian resolution $key not found. Generating on the fly..."
    raw_data = load_sim_data(params, Val(:raw))
    
    conv_data = if raw_data isa LSimData
        convert_to_eulerian(raw_data, res)
    else
        resample_eulerian(raw_data, res)
    end
    
    # --- NEW: Conditionally cache the generated conversion ---
    if _ENABLE_CONV_CACHE[]
        jldopen(file_name, "a+") do file
            # Safe check in case of thread race conditions
            if !haskey(file, key)
                file[key] = conv_data
            end
        end
    end
    
    return conv_data
end

function load_sim_data(params::ParamDict, ::Val{:lagrangian})
    file_name = get_file_name(params)
    native = _get_native_type(file_name)
    
    if native == :lagrangian
        return load_sim_data(params, Val(:raw))
    else
        # Directly load the L-conversion or generate it
        has_conv = jldopen(file_name, "r") do file; haskey(file, "conv_L"); end
        
        if has_conv
            return jldopen(file_name, "r") do file; file["conv_L"]; end
        else
            @info "Lagrangian conversion not found. Generating on the fly..."
            raw_data = load_sim_data(params, Val(:raw))
            conv_data = convert_to_lagrangian(raw_data)
            
            # --- NEW: Conditionally cache the generated conversion ---
            if _ENABLE_CONV_CACHE[]
                jldopen(file_name, "a+") do file
                    if !haskey(file, "conv_L")
                        file["conv_L"] = conv_data
                    end
                end
            end
            
            return conv_data
        end
    end
end

# ==============================================================================
# --- EXISTENCE CHECKERS ---
# ==============================================================================

does_sim_data_exist(params::ParamDict) = does_sim_data_exist(params, Val(:raw))

function does_sim_data_exist(params::ParamDict, ::Val{:raw})
    try
        return jldopen(get_file_name(params), "r") do file; haskey(file, "raw"); end
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function does_sim_data_exist(params::ParamDict, ::Val{:eulerian}, res::Tuple)
    try
        file_name = get_file_name(params)
        native = _get_native_type(file_name)
        
        if native == :eulerian
            # If native is Eulerian, check if the raw data perfectly matches the requested resolution
            is_perfect_match = jldopen(file_name, "r") do file
                raw = file["raw"]
                return size(raw.u) == res
            end
            
            if is_perfect_match
                return true
            end
        end
        
        # If not a perfect raw match (or native is Lagrangian), check for the explicit cached key
        target_key = get_conv_key(res)
        return jldopen(file_name, "r") do file; haskey(file, target_key); end
        
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function does_sim_data_exist(params::ParamDict, ::Val{:lagrangian})
    try
        file_name = get_file_name(params)
        native = _get_native_type(file_name)
        
        if native == :lagrangian
            # If native is Lagrangian, we just need the raw data
            return jldopen(file_name, "r") do file; haskey(file, "raw"); end
        else
            # If native is Eulerian, check for the specific L-conversion key
            return jldopen(file_name, "r") do file; haskey(file, "conv_L"); end
        end
        
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function load_sim_data(hash_prefix::String; index::Int=1)
    clean_prefix = replace(hash_prefix, ".jld2" => "")
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)
    candidates = filter(f -> occursin(clean_prefix, f) && endswith(f, ".jld2"), all_files)
    
    if isempty(candidates)
         throw(SimFileNotFoundError("No files found matching the hash prefix: $clean_prefix"))
    end

    sort!(candidates, by = f -> mtime(joinpath(save_data, f)), rev=true)
    
    if index > length(candidates) || index < 1
        error("Requested index $index, but only $(length(candidates)) files match the hash '$clean_prefix'.")
    end

    file_name = joinpath(save_data, candidates[index])
    @info "Manual Load: Found $(length(candidates)) matching files. Loading index $index: $(candidates[index])"
    
    # Pure passthrough load to the primary raw data
    return JLD2.load(file_name)
end

"""
    check_data(data::AbstractSimData)

Generates a fast, allocation-free DataFrame summarizing the Min, Max, Mean, 
and NaN count for every component at every timestep. Works natively on both 
ESimData and LSimData.
"""
function check_data(data::AbstractSimData)
    T_len = length(data.t)
    
    # Dynamically determine the number of components (M)
    M = if data isa ESimData
        size(data.u, 1)
    else
        # For Lagrangian, peek at the first valid particle of the first timestep
        length(data.u) > 0 && length(data.u[1]) > 0 ? length(data.u[1][1]) : 1
    end
    
    # Preallocate the dictionary to build the DataFrame
    df_dict = Dict{Symbol, Vector{Float64}}()
    df_dict[:Time] = data.t
    
    for c in 1:M
        df_dict[Symbol("C$(c)_Min")]  = zeros(T_len)
        df_dict[Symbol("C$(c)_Max")]  = zeros(T_len)
        df_dict[Symbol("C$(c)_Mean")] = zeros(T_len)
        df_dict[Symbol("C$(c)_NaNs")] = zeros(T_len)
    end
    
    for m in 1:T_len
        for c in 1:M
            # Fast, allocation-free accumulators
            min_v, max_v = Inf, -Inf
            sum_v = 0.0
            valid_count, nan_count = 0, 0
            
            # 1. Extract the data iterator based on the struct type
            iterator = if data isa ESimData
                # Slice: [Component, X, Y, Z..., Time] -> extract specific component & time
                selectdim(selectdim(data.u, ndims(data.u), m), 1, c)
            else
                # Map lazily over the particles at this timestep
                (p[c] for p in data.u[m])
            end
            
            # 2. Single-pass evaluation (Zero memory allocations!)
            for val in iterator
                if isnan(val)
                    nan_count += 1
                else
                    min_v = min(min_v, val)
                    max_v = max(max_v, val)
                    sum_v += val
                    valid_count += 1
                end
            end
            
            # 3. Save to our DataFrame dictionary
            df_dict[Symbol("C$(c)_NaNs")][m] = nan_count
            
            if valid_count > 0
                df_dict[Symbol("C$(c)_Min")][m]  = min_v
                df_dict[Symbol("C$(c)_Max")][m]  = max_v
                df_dict[Symbol("C$(c)_Mean")][m] = sum_v / valid_count
            else
                df_dict[Symbol("C$(c)_Min")][m]  = NaN
                df_dict[Symbol("C$(c)_Max")][m]  = NaN
                df_dict[Symbol("C$(c)_Mean")][m] = NaN
            end
        end
    end
    
    # Construct the DataFrame and force the 'Time' column to be first
    df = DataFrame(df_dict)
    select!(df, :Time, Not(:Time))
    
    return df
end


"""
Deletes all saved simulation meshes with the given keys and values in its parameter dictionary.
"""
function delete_sim_data(keys::Vector{Symbol}, vals::Vector)
    save_data = get_save_path() * "/data/"
    if !isdir(save_data); return; end
    
    files = readdir(save_data)
    for file in files
        if !endswith(file, ".jld2"); continue; end
        
        full_path = joinpath(save_data, file)
        try
            sim_data = load(full_path, "raw")
            deletion = true
            for (i,key) in enumerate(keys)
                # Now safely comparing against a strictly typed ParamDict
                if !haskey(sim_data.params, key) || !(sim_data.params[key] == vals[i])
                    deletion = false
                    break
                end
            end
            
            if deletion
                @warn "Deleting file matching criteria: $file"
                rm(full_path)
            end
        catch e
            @warn "Could not load file $file for deletion check" exception=e
        end
    end
end

"""
    rehash_sim_data(target_path::String; kwargs...)

Recursively scans a directory (or processes a single file) for .jld2 simulation files,
cleans the parameters, and saves under a new hash.

Keyword Arguments:
* `delete_old::Bool=true`: Removes the old file after a successful rehash.
* `filter_pairs::Union{Dict{Symbol, Any}, Nothing}=nothing`: Only processes files containing these exact parameter matches (e.g., `Dict(:Ns => (500,))`).
* `remove_keys::Vector{Symbol}=Symbol[]`: Deletes these keys from the parameter dictionary before rehashing.
* `prompt_keys::Vector{Symbol}=Symbol[]`: Pauses on each matched file, prints current parameters, and prompts the user in the REPL to input values for these keys.
"""
function rehash_sim_data(
    target_path::String; 
    delete_old::Bool=true,
    filter_pairs::Union{Dict{Symbol, <:Any}, Nothing}=nothing,
    remove_keys::Vector{Symbol}=Symbol[],
    prompt_keys::Vector{Symbol}=Symbol[]
)
    if isfile(target_path) && endswith(target_path, ".jld2")
        _rehash_single_file(target_path, delete_old, filter_pairs, remove_keys, prompt_keys)
    elseif isdir(target_path)
        for (root, dirs, files) in walkdir(target_path)
            for file in files
                if endswith(file, ".jld2")
                    _rehash_single_file(joinpath(root, file), delete_old, filter_pairs, remove_keys, prompt_keys)
                end
            end
        end
    else
        @warn "Path is neither a .jld2 file nor a directory: $target_path"
    end
end

function _rehash_single_file(file_path::String, delete_old::Bool, filter_pairs, remove_keys, prompt_keys)
    local raw_data
    try
        jldopen(file_path, "r") do file
            if !haskey(file, "raw")
                return nothing
            end
            raw_data = file["raw"]
        end
    catch e
        @warn "Failed to open $(basename(file_path))" exception=e
        return
    end

    isnothing(raw_data) && return

    # --- FILTERING ---
    if !isnothing(filter_pairs)
        skip = false
        for (k, v) in filter_pairs
            # Direct comparison (catches both stringified and raw values if typed correctly)
            if !haskey(raw_data.params, k) || raw_data.params[k] != v
                skip = true
                break
            end
        end
        skip && return
    end
    
    @info "Processing matched file: $(basename(file_path))"

    # --- REMOVAL ---
    for k in remove_keys
        if haskey(raw_data.params, k)
            delete!(raw_data.params, k)
            @info "  Removed obsolete key: $k"
        end
    end

    # --- INTERACTIVE PROMPTING ---
    if !isempty(prompt_keys)
        println("\n--- Current Parameters for $(basename(file_path)) ---")
        for (k, v) in raw_data.params
            println("  $k => $(val2str(v))")
        end
        println("---------------------------------------------------")
        
        for pk in prompt_keys
            print("Enter value for '$pk' (valid Julia expression, leave blank to skip): ")
            val_str = strip(readline())
            if !isempty(val_str)
                try
                    # Evaluate the user's string as native Julia code (e.g. typing [1, 2] creates a Vector)
                    val = eval(Meta.parse(val_str))
                    raw_data.params[pk] = val
                    @info "  Injected: $pk = $val"
                catch e
                    @warn "  Failed to parse '$val_str'. Skipping '$pk'."
                end
            else
                @info "  Skipped '$pk'."
            end
        end
    end

    # --- NORMALIZATION & HASHING ---
    condensed_params = Dict{Symbol, Any}()
    for (k, v) in raw_data.params
        condensed_params[k] = str2val(val2str(v))
    end
    
    empty!(raw_data.params)
    merge!(raw_data.params, condensed_params)

    new_hash = calculate_hash(raw_data.params)
    
    bname = basename(file_path)
    m = match(r"^(.+)_([a-f0-9a-fA-F]+)\.jld2$", bname)
    timestamp = !isnothing(m) ? m.captures[1] : Dates.format(Dates.now(), "yyyy-mm-dd_HH-MM-SS_sss")
    
    new_file_name = "$(timestamp)_$(new_hash).jld2"
    new_file_path = joinpath(dirname(file_path), new_file_name)
    
    # --- SAFE FILE SWAP ---
    temp_file = new_file_path * ".tmp"
    try
        jldopen(temp_file, "w") do file
            file["raw"] = raw_data
            file["native"] = raw_data isa ESimData ? :eulerian : :lagrangian
            file["params"] = raw_data.params
            file["stat_keys"] = collect(keys(raw_data.stats))
        end
        
        is_same_file = abspath(file_path) == abspath(new_file_path)
        
        if delete_old && !is_same_file
            rm(file_path, force=true)
            @info "Rehashed and renamed: $bname -> $new_file_name\n"
        elseif is_same_file
            @info "Rehashed in-place (hash unchanged): $bname\n"
        else
            @info "Rehashed and copied (old file kept): $bname -> $new_file_name\n"
        end
        
        mv(temp_file, new_file_path, force=true)
        
    catch e
        @error "Failed to write $new_file_name" exception=e
        rm(temp_file, force=true)
    end
end

"""
    get_clean_params(params::Dict)
    get_clean_params(sim_data::AbstractSimData)

Returns a dictionary where all values have been scrubbed by normalization function. Useful for debugging serialization signatures.
"""
function get_clean_params(params::Dict)
    clean_dict = Dict{Symbol, Any}()
    for (k, v) in params
        clean_dict[k] = str2val(val2str(v))
    end
    return clean_dict
end

get_clean_params(sim_data) = get_clean_params(sim_data.params)

"""
    print_clean_params(data)

Neatly prints the scrubbed parameters to the REPL in alphabetical order. 
Accepts either a Parameter Dictionary or an AbstractSimData object.
"""
function print_clean_params(data)
    clean_dict = get_clean_params(data)
    println("\n--- Cleaned Parameters ---")
    for (k, v) in sort(collect(clean_dict), by=x->string(x[1]))
        println("  $k => $v")
    end
    println("--------------------------\n")
    return clean_dict
end