"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end


"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            @info "Created save directory: $abs_path"
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        @info "Module save root path set to: $(_SAVE_ROOT_PATH[])"

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    @info "Created subdirectory: $subdir_path"
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



"""
Calculates the hash of a given params dictionary
"""
function calculateHash(params::ParamDict)
    sorted_keys = sort(collect(keys(params)))
    stringToHash = join(map(key -> "$key => $(params[key])", sorted_keys))
    return bytes2hex(sha256(stringToHash))
end
function getFileName(params::ParamDict)
    hash_val = calculateHash(params)
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)
    candidate_files = filter(f -> (endswith(f, "_$(hash_val).jld2") || startswith(f, "$(hash_val)_")) && endswith(f, ".jld2"), all_files)

    if isempty(candidate_files)
        throw(SimFileNotFoundError("File with matching parameters not found."))
    end

    sort!(candidate_files, by = f -> mtime(joinpath(save_data, f)), rev=true)
    
    # --- THE FIX: Exact Parameter Match Resolution ---
    for file in candidate_files
        full_path = joinpath(save_data, file)
        try
            is_match = jldopen(full_path, "r") do f
                # Grab the first available key to inspect its parameters
                if !isempty(keys(f))
                    first_key = first(keys(f))
                    saved_params = f[first_key].params
                    return saved_params == params
                end
                return false
            end
            
            if is_match
                return full_path
            end
        catch e
            @warn "Could not read $file during hash collision check." exception=e
            continue
        end
    end

    throw(SimFileNotFoundError("Hash matched, but exact parameters did not match any file."))
end

function saveSimData(sim_data::AbstractSimData; overwrite::Bool = false)
    file_name = ""
    try
        file_name = getFileName(sim_data.params)
    catch e
        if !isa(e, SimFileNotFoundError); rethrow(e); end
    end

    # 1. New File Initialization
    if isempty(file_name)
        hash_val = calculateHash(sim_data.params)
        timestamp = Dates.format(now(), "yyyy-mm-dd_HH-MM-SS_sss")
        save_data = joinpath(get_save_path(), "data")
        if !isdir(save_data); mkpath(save_data); end
        
        file_name = joinpath(save_data, "$(timestamp)_$(hash_val).jld2")
        mode = "w"
        target_key = "raw"
    else
        mode = "a+"
        
        # 2. Determine Key based on Base Type mapping
        target_key = jldopen(file_name, "r") do file
            if haskey(file, "raw")
                raw_data = file["raw"]
                
                # If they are the exact same paradigm, we overwrite raw
                is_same_base = (sim_data isa ESimData && raw_data isa ESimData) || 
                               (sim_data isa LSimData && raw_data isa LSimData)
                
                if is_same_base
                    return "raw"
                elseif sim_data isa ESimData
                    # Lagrangian -> Eulerian (needs grid resolution)
                    return "conv_$(_N_GRID[])_$(_T_GRID[])"
                else
                    # Eulerian -> Lagrangian (unique representation, no grid needed)
                    return "conv"
                end
            else
                return "raw" # Fallback if file exists but is empty
            end
        end
    end

    # 3. Save the Data
    jldopen(file_name, mode) do file
        if haskey(file, target_key)
            if overwrite
                delete!(file, target_key)
                file[target_key] = sim_data
                @info "Overwrote existing '$target_key' in $(basename(file_name))"
                
                # --- THE FIX: Clear outdated conversions if overwriting raw ---
                if target_key == "raw"
                    for k in keys(file)
                        if startswith(k, "conv")
                            delete!(file, k)
                            @info "Cleared outdated conversion cache: '$k'"
                        end
                    end
                end
                
            else
                @info "'$target_key' already exists in $(basename(file_name)). Skipping save."
            end
        else
            file[target_key] = sim_data
            @info "Saved '$target_key' to $(basename(file_name))"
        end
        
        # --- Save native metadata instantly ---
        if target_key == "raw"
            native_str = sim_data isa ESimData ? :eulerian : :lagrangian
            if haskey(file, "native")
                delete!(file, "native")
            end
            file["native"] = native_str
        end
    end
end

# Default fallback routes to :raw
loadSimData(params::ParamDict) = loadSimData(params, Val(:raw))

# --- Fast Metadata Reader ---
function _get_native_type(file_name::String)
    return jldopen(file_name, "r") do file
        if haskey(file, "native")
            return file["native"]
        else
            # Backwards compatibility for older JLD2 files
            return typeof(file["raw"]) <: ESimData ? :eulerian : :lagrangian
        end
    end
end

# ==============================================================================
# --- LOAD ROUTERS ---
# ==============================================================================

function loadSimData(params::ParamDict, ::Val{:raw})
    file_name = getFileName(params)
    return jldopen(file_name, "r") do file
        haskey(file, "raw") ? file["raw"] : throw(SimFileNotFoundError("Key 'raw' not found."))
    end
end

function loadSimData(params::ParamDict, ::Val{:conv})
    file_name = getFileName(params)
    native = _get_native_type(file_name)
    target_key = native == :lagrangian ? "conv_$(_N_GRID[])_$(_T_GRID[])" : "conv"
    
    has_conv = jldopen(file_name, "r") do file; haskey(file, target_key); end
    if has_conv
        return jldopen(file_name, "r") do file; file[target_key]; end
    end
    
    @info "Converted format '$target_key' not found. Generating on the fly..."
    raw_data = loadSimData(params, Val(:raw))
    conv_data = native == :lagrangian ? convert_to_eulerian(raw_data) : convert_to_lagrangian(raw_data)
    
    saveSimData(conv_data; overwrite=true) 
    return conv_data
end

# The User's Brilliant 1-Line Semantic Routers!
function loadSimData(params::ParamDict, ::Val{:eulerian})
    native = _get_native_type(getFileName(params))
    return native == :eulerian ? loadSimData(params, Val(:raw)) : loadSimData(params, Val(:conv))
end

function loadSimData(params::ParamDict, ::Val{:lagrangian})
    native = _get_native_type(getFileName(params))
    return native == :lagrangian ? loadSimData(params, Val(:raw)) : loadSimData(params, Val(:conv))
end

# ==============================================================================
# --- EXISTENCE CHECKERS ---
# ==============================================================================

doesSimDataExist(params::ParamDict) = doesSimDataExist(params, Val(:raw))

function doesSimDataExist(params::ParamDict, ::Val{:raw})
    try
        return jldopen(getFileName(params), "r") do file; haskey(file, "raw"); end
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function doesSimDataExist(params::ParamDict, ::Val{:conv})
    try
        file_name = getFileName(params)
        native = _get_native_type(file_name)
        target_key = native == :lagrangian ? "conv_$(_N_GRID[])_$(_T_GRID[])" : "conv"
        return jldopen(file_name, "r") do file; haskey(file, target_key); end
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function doesSimDataExist(params::ParamDict, ::Val{:eulerian})
    try
        native = _get_native_type(getFileName(params))
        return native == :eulerian ? doesSimDataExist(params, Val(:raw)) : doesSimDataExist(params, Val(:conv))
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function doesSimDataExist(params::ParamDict, ::Val{:lagrangian})
    try
        native = _get_native_type(getFileName(params))
        return native == :lagrangian ? doesSimDataExist(params, Val(:raw)) : doesSimDataExist(params, Val(:conv))
    catch e
        return isa(e, SimFileNotFoundError) ? false : rethrow(e)
    end
end

function loadSimData(hash_prefix::String; index::Int=1)
    clean_prefix = replace(hash_prefix, ".jld2" => "")
    save_data = joinpath(get_save_path(), "data")
    
    if !isdir(save_data)
        throw(SimFileNotFoundError("Data directory does not exist."))
    end

    all_files = readdir(save_data)
    candidates = filter(f -> occursin(clean_prefix, f) && endswith(f, ".jld2"), all_files)
    
    if isempty(candidates)
         throw(SimFileNotFoundError("No files found matching the hash prefix: $clean_prefix"))
    end

    sort!(candidates, by = f -> mtime(joinpath(save_data, f)), rev=true)
    
    if index > length(candidates) || index < 1
        error("Requested index $index, but only $(length(candidates)) files match the hash '$clean_prefix'.")
    end

    file_name = joinpath(save_data, candidates[index])
    @info "Manual Load: Found $(length(candidates)) matching files. Loading index $index: $(candidates[index])"
    
    # Pure passthrough load to the primary raw data
    return JLD2.load(file_name)
end

"""
    check_data(data::AbstractSimData)

Generates a fast, allocation-free DataFrame summarizing the Min, Max, Mean, 
and NaN count for every component at every timestep. Works natively on both 
ESimData and LSimData.
"""
function check_data(data::AbstractSimData)
    T_len = length(data.t)
    
    # Dynamically determine the number of components (M)
    M = if data isa ESimData
        size(data.u, 1)
    else
        # For Lagrangian, peek at the first valid particle of the first timestep
        length(data.u) > 0 && length(data.u[1]) > 0 ? length(data.u[1][1]) : 1
    end
    
    # Preallocate the dictionary to build the DataFrame
    df_dict = Dict{Symbol, Vector{Float64}}()
    df_dict[:Time] = data.t
    
    for c in 1:M
        df_dict[Symbol("C$(c)_Min")]  = zeros(T_len)
        df_dict[Symbol("C$(c)_Max")]  = zeros(T_len)
        df_dict[Symbol("C$(c)_Mean")] = zeros(T_len)
        df_dict[Symbol("C$(c)_NaNs")] = zeros(T_len)
    end
    
    for m in 1:T_len
        for c in 1:M
            # Fast, allocation-free accumulators
            min_v, max_v = Inf, -Inf
            sum_v = 0.0
            valid_count, nan_count = 0, 0
            
            # 1. Extract the data iterator based on the struct type
            iterator = if data isa ESimData
                # Slice: [Component, X, Y, Z..., Time] -> extract specific component & time
                selectdim(selectdim(data.u, ndims(data.u), m), 1, c)
            else
                # Map lazily over the particles at this timestep
                (p[c] for p in data.u[m])
            end
            
            # 2. Single-pass evaluation (Zero memory allocations!)
            for val in iterator
                if isnan(val)
                    nan_count += 1
                else
                    min_v = min(min_v, val)
                    max_v = max(max_v, val)
                    sum_v += val
                    valid_count += 1
                end
            end
            
            # 3. Save to our DataFrame dictionary
            df_dict[Symbol("C$(c)_NaNs")][m] = nan_count
            
            if valid_count > 0
                df_dict[Symbol("C$(c)_Min")][m]  = min_v
                df_dict[Symbol("C$(c)_Max")][m]  = max_v
                df_dict[Symbol("C$(c)_Mean")][m] = sum_v / valid_count
            else
                df_dict[Symbol("C$(c)_Min")][m]  = NaN
                df_dict[Symbol("C$(c)_Max")][m]  = NaN
                df_dict[Symbol("C$(c)_Mean")][m] = NaN
            end
        end
    end
    
    # Construct the DataFrame and force the 'Time' column to be first
    df = DataFrame(df_dict)
    select!(df, :Time, Not(:Time))
    
    return df
end


"""
Deletes all saved simulation meshes with the given keys and values in its parameter dictionary.
"""
function deleteSimData(keys::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    if !isdir(save_data); return; end
    
    files = readdir(save_data)
    for file in files
        if !endswith(file, ".jld2"); continue; end
        
        full_path = joinpath(save_data, file)
        try
            sim_data = load(full_path, "raw")
            deletion = true
            for (i,key) in enumerate(keys)
                # Check if key exists and matches value/type
                if !haskey(sim_data.params, key) || !(sim_data.params[key] == vals[i])
                    deletion = false
                    break
                end
            end
            
            if deletion
                @warn "Deleting file matching criteria: $file"
                rm(full_path)
            end
        catch e
            @warn "Could not load file $file for deletion check" exception=e
        end
    end
end

