module Utils

using ..Structs  

using SHA
using CSV, DataFrames
using JLD2, FileIO

export saveSimData,calculateHash, getFileName, loadSimData, getStats, doesSimDataExist, deleteSimData, 
       getAllSavedMeshes, changeStats, set_save_path!, get_save_path


const _SAVE_ROOT_PATH = Ref{String}(pwd())

"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            println("Created save directory: $abs_path")
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        println("Module save root path set to: $(_SAVE_ROOT_PATH[])")

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    println("Created subdirectory: $subdir_path")
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



"""
Calculates the hash of a given params dictionary
"""
function calculateHash(params::ParamDictType)
    sorted_keys = sort(collect(keys(params)))
    sorted_vals = [params[key] for key = sorted_keys]
    stringToHash = join(map(d -> "$d", sorted_vals))
    return bytes2hex(sha256(stringToHash))
end

"""
Saves the given simulation mesh in the folder given by save_data with the hash as the filename.

CAUTION: Enabling overwrite will overwrite an existing file with the given simulation mesh!
"""
function saveSimData(SimData::AbstractSimData; overwrite::Bool = false)
    hash = calculateHash(SimData.params)
    save_data = get_save_path() * "/data/"
    file_name = save_data * hash *".jld2"
    counter = 0
    while true
        counter += 1
        if !isfile(file_name)
            save(file_name, "SimData", SimData)
            break
        else
            SimDataSaved = load(file_name)["SimData"]
            if !(SimData.params == SimDataSaved.params)
                print("Filename already exists! Changing hash...")
                file_name = save_data * hash * "_$counter.jld2"
            else
                if overwrite
                    println("Simulation mesh has been overwritten!")
                    save(file_name, "SimData", SimData)
                else
                    println("File already exists!")
                end
                break
            end 
        end
    end
end

"""
Returns the filename of the simulation data corresponding to the given params dictionary
"""
function getFileName(params::ParamDictType)
    hash = calculateHash(params)
    save_data = get_save_path() * "/data/"
    file = save_data * hash *".jld2"
    counter = 0
    while true
        counter += 1
        if isfile(file)
            SimDataSaved = load(file)["SimData"]
            if (params == SimDataSaved.params)
                return file_name
            else
                file_name = hash * "_$counter"
                file = save_data * file_name * ".jld2"
            end
        else
            error("Requested File does not exist! Make sure you ran the simulation!")
        end
    end
end

"""
Loads the simulation data corresponding to the given params dictionary as a simulation mesh
"""
function loadSimData(params::ParamDictType)
    save_data = get_save_path() * "/data/"
    file_name = save_data * getFileName(params) * ".jld2"
    return load(file_name)["SimData"]
end
function loadSimData(hash::String)
    save_data = get_save_path() * "/data/"
    file_name = save_data * hash *".jld2"
    return load(file_name)["SimData"]
end

"""
Loads only the stats field of the simulation mesh
"""
function getStats(params::ParamDictType)
    SimData = loadSimData(params)
    return SimData.stats
end

"""
Checks if simulation data already exists for the given paramseter dictionary
"""
function doesSimDataExist(params::ParamDictType)
    try getFileName(params)
        return true
    catch e
        return false
    end
end

"""
Deletes all saved simulation meshes with the given keys and values in its paramseter dictionary.
"""
function deleteSimData(keys::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        SimData = load(save_data * file)["SimData"]
        deletion = true
        for (i,key) = enumerate(keys)
            deletion = deletion && (SimData.params[key] == vals[i]) && (SimData.params[key] isa typeof(vals[i]))
        end
        if deletion
            println("Saved data is being deleted!")
            rm(save_data * file)
        end
    end
end

"""
Changes the paramseter dictionary of a simulation mesh from the old values to the new ones. Helpful if unused paramseters need to be changed or the type 
is wrong (e.g. Int instead of Float). Note that the values are not changed, hence use with caution.

"""
function changeparams(ks::Vector{String}, oldVals::Vector, newVals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        SimData = load(save_data * file)["SimData"]
        for (i,key) = enumerate(ks)
            if (key in keys(SimData.params))
                if SimData.params[key] == oldVals[i]
                    SimData.params[key] = newVals[i]
                    saveSimData(SimData; overwrite = true)
                    println("Changed simulation mesh is saved!")
                end
            end
        end
    end
end

"""
Returns all saved simulation meshes with the given paramseters.
"""
function getAllSavedMeshes(ks::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    res = []
    files = readdir(save_data)
    for file = files
        SimData = load(save_data * file)["SimData"]
        hit = true
        for (i,key) = enumerate(ks)
            if (key in keys(SimData.params))
                hit = hit & (SimData.params[key] == vals[i])
            else
                hit = false
            end
        end
        if hit
            push!(res, SimData)
        end
    end
    return res
end

"""
Changes the given stat of all simulation meshes using the given function f. The function has to be of the
form f(u,x) or f(u,x,t) for the static and dynamic case respectively. It can also be used to add a new stat
to the simulation meshes.
"""
function changeStats(statsName::String, f::Function, simulation::String)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        SimData = load(save_data * file)["SimData"]
        if SimData.params["simulation"] == simulation
            if simulation == "PDE"
                SimData.stats[statsName] = f(SimData.u, SimData.x, SimData.t)
            else
                SimData.stats[statsName] = f(SimData.u, SimData.x)
            end
            saveSimData(SimData; overwrite = true)
        end
    end    
end

end