module Utils

using ..Structs  

using SHA
using CSV, DataFrames
using JLD2, FileIO
using Base.Threads
using GLMakie
using ProgressMeter 
using LibGit2

export saveSimData, calculateHash, getFileName, loadSimData, getStats, doesSimDataExist, deleteSimData, 
       getAllSimData, changeStats, set_save_path!, get_save_path, StringToTuple, 
       assembleParams, allMethodNames, create_sim_config_from_csv, load_additional_options_from_csv, createObsDict, connectObsDict!


const _SAVE_ROOT_PATH = Ref{String}(pwd())

"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end


"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            @info "Created save directory: $abs_path"
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        @info "Module save root path set to: $(_SAVE_ROOT_PATH[])"

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    @info "Created subdirectory: $subdir_path"
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



"""
Calculates the hash of a given params dictionary
"""
function calculateHash(params::ParamDictType)
    sorted_keys = sort(collect(keys(params)))
    stringToHash = join(map(key -> "$key => $(params[key])", sorted_keys))
    return bytes2hex(sha256(stringToHash))
end

"""
Saves the given simulation mesh in the folder given by save_data with the hash as the filename.

CAUTION: Enabling overwrite will overwrite an existing file with the given simulation mesh!
"""
function saveSimData(sim_data::AbstractSimData; overwrite::Bool = false)

    hash = calculateHash(sim_data.params)
    save_data = get_save_path() * "/data/"
    file_name = save_data * hash *".jld2"
    counter = 0
    while true
        counter += 1
        if !isfile(file_name)
            save(file_name, "sim_data", sim_data)
            @info "SimData saved to file $file_name"
            break
        else
            SimDataSaved = load(file_name)["sim_data"]
            if !(sim_data.params == SimDataSaved.params)
                @info "Filename already exists! Changing hash..."
                file_name = save_data * hash * "_$counter.jld2"
            else
                if overwrite
                    save(file_name, "sim_data", sim_data)
                    @warn "Simulation mesh has been overwritten!"
                    @info "SimData saved to file $file_name"
                else
                    @info "File already exists!"
                end
                break
            end 
        end
    end
end

"""
Returns the filename of the simulation data corresponding to the given params dictionary.
Throws SimFileNotFoundError if no matching file is found.
"""
function getFileName(params::ParamDictType)
    
    local file_name # Ensure file_name is scoped correctly
    hash_val = calculateHash(params) # Renamed from 'hash' to avoid conflict
    save_data = get_save_path() * "/data/"
    base_file_part = save_data * hash_val
    file = base_file_part * ".jld2"
    counter = 0

    while true
        # Construct current filename to check
        if counter == 0
            file_name = hash_val # Assign base name
        else
            file_name = hash_val * "_$(counter-1)" # Use counter-1 for _0, _1, ...
            file = save_data * file_name * ".jld2"
        end

        if isfile(file)
            try # Add inner try-catch for loading/comparison errors
                sim_data_saved = load(file)["sim_data"]
                if (params == sim_data_saved.params)
                    @info "Found matching file: ", file # Debug print
                    return file # Return the full path
                else
                    println("Input",params)
                    println("Saved",sim_data_saved.params)
                    # Hash collision, prepare to check next file in the next iteration
                    @warn "Hash collision detected for: ", file # Debug print
                    counter += 1
                    # Continue to the next iteration of the while loop
                end
            catch load_err
                 # Error during loading or comparison, treat as if file doesn't match
                 @warn "Error processing potential match file '$file'. Skipping." exception=(load_err, catch_backtrace())
                 counter += 1 # Prepare to check next file
            end
        else
            # If we checked the base file (counter=0) and it wasn't there, OR
            # if we checked a collision file (_N) and it wasn't there,
            # then no matching file exists with this base hash.
            @info "File not found: ", file, ". Stopping search for this hash." # Debug print
            throw(SimFileNotFoundError("Requested File does not exist! (Checked up to collision $counter)"))
            # The loop terminates here by throwing the error
        end

        # Optional: Add a safety break to prevent infinite loops in unexpected scenarios
        if counter > 100 # Or some other reasonable limit
             @warn "Exceeded collision check limit for hash $hash_val. Assuming file not found."
             throw(SimFileNotFoundError("Exceeded collision check limit for hash $hash_val."))
        end
    end
end

"""
Loads the simulation data corresponding to the given params dictionary as a simulation mesh
"""
function loadSimData(params::ParamDictType)
    return load(getFileName(params))["sim_data"]
end
function loadSimData(hash::String)
    save_data = get_save_path() * "/data/"
    file_name = save_data * hash *".jld2"
    return load(file_name)["sim_data"]
end

"""
Loads only the stats field of the simulation mesh
"""
function getStats(params::ParamDictType)
    sim_data = loadSimData(params)
    return sim_data.stats
end

"""
Checks if simulation data already exists for the given parameter dictionary.
Returns true if found, false only if specifically not found (SimFileNotFoundError).
Other errors during check will propagate.
"""
function doesSimDataExist(params::ParamDictType)
    try
        getFileName(params) # Call the function that might throw
        # If getFileName returns successfully, it means a matching file was found
        return true
    catch e
        #e = nothing
        if isa(e, SimFileNotFoundError)
            # This is the specific error indicating the file wasn't found.
            # This is NOT a bug, it's the expected outcome when data doesn't exist.
             # println("Debug (doesSimDataExist): Caught expected SimFileNotFoundError: ", e.message) # Optional
            return false # File not found, return false as intended
        else
            # This is some other, unexpected error (e.g., in calculateHash, get_save_path,
            # permissions, JLD2 issues, logic errors in getFileName).
            # We DON'T want to mask this!
            @error "Unexpected error during file existence check!" exception=(e, catch_backtrace())
            rethrow(e) # Re-throw the unexpected error to halt and allow debugging
        end
    end
end

"""
Deletes all saved simulation meshes with the given keys and values in its paramseter dictionary.
"""
function deleteSimData(keys::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        deletion = true
        for (i,key) = enumerate(keys)
            deletion = deletion && (sim_data.params[key] == vals[i]) && (sim_data.params[key] isa typeof(vals[i]))
        end
        if deletion
            @warn "Saved data at $file is being deleted!"
            rm(save_data * file)
        end
    end
end

"""
Changes the paramseter dictionary of a simulation mesh from the old values to the new ones. Helpful if unused paramseters need to be changed or the type 
is wrong (e.g. Int instead of Float). Note that the values are not changed, hence use with caution.

"""
function changeparams(ks::Vector{String}, oldVals::Vector, newVals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                if sim_data.params[key] == oldVals[i]
                    sim_data.params[key] = newVals[i]
                    saveSimData(sim_data; overwrite = true)
                    @info "Changed simulation mesh is saved!"
                end
            end
        end
    end
end

"""
Returns all saved simulation meshes with the given paramseters.
"""
function getAllSimData(ks::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    res = []
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        hit = true
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                hit = hit & (sim_data.params[key] == vals[i])
            else
                hit = false
            end
        end
        if hit
            push!(res, sim_data)
        end
    end
    return res
end

"""
Changes the given stat of all simulation meshes using the given function f. The function has to be of the
form f(u,x) or f(u,x,t) for the static and dynamic case respectively. It can also be used to add a new stat
to the simulation meshes.
"""
function changeStats(statsName::String, f::Function, simulation::String)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        if sim_data.params["simulation"] == simulation
            if simulation == "PDE"
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x, sim_data.t)
            else
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x)
            end
            saveSimData(sim_data; overwrite = true)
        end
    end    
end

"""
    string_to_typed_tuple(s::String)::Union{Tuple, Nothing}

Attempts to parse a string representation of a tuple containing elements
that can be interpreted as Bool, Int, or Float64 into a Julia `Tuple`.
The types of the elements in the output tuple will reflect the parsed values
(e.g., could be Tuple{Float64, Bool, Int64}).

The string should be in a format like "(1.0, true, -3)".
It handles:
- Leading/trailing whitespace around the string itself.
- Whitespace around numbers, booleans, and commas within the parentheses.
- Empty tuple "()".
- Single-element tuples like "(1.23)", "(true,)", or "(1, )".
- Multiple elements like "(1.0, false, 2)".

Returns the parsed tuple (e.g., `(1.0, true, -3)`) if successful,
or `nothing` if the string is not in the expected format or if any
element cannot be parsed as Bool, Int, or Float64.

# Examples
```jldoctest
julia> string_to_typed_tuple("(1.0, true, -3)")
(1.0, true, -3)

julia> string_to_typed_tuple("( 42,  false )")
(42, false)

julia> string_to_typed_tuple("(3.14,)")
(3.14,)

julia> string_to_typed_tuple("()")
()

julia> string_to_typed_tuple("not a tuple") # returns nothing

julia> string_to_typed_tuple("(1, abc, 3)") # returns nothing

julia> string_to_typed_tuple("(1.0, , 2.0)") # returns nothing
```
"""
function StringToTuple(s::String)::Union{Tuple, Nothing}
    # Strip leading/trailing whitespace from the whole string
    s_stripped = strip(s)

    if s_stripped == "()" return () end

    # Check for enclosing parentheses
    if !startswith(s_stripped, "(") || !endswith(s_stripped, ")")
        return nothing
    end

    # Extract content within parentheses
    if length(s_stripped) < 2 # Should only be true for malformed like "("
        return nothing
    end
    content = s_stripped[begin+1:end-1]
    
    # Handle empty tuple case like "()" -> content is ""
    if isempty(strip(content))
        return () # Return an empty tuple of type Tuple{}
    end

    # Split by comma
    parts_str = split(content, ',')
    
    # Handle potential empty string from a trailing comma before the closing parenthesis
    # e.g., content "1.0," or "1.0, 2.0,"
    # A robust way to check for trailing comma: if the original content (after stripping outer parens)
    # ended with a comma, and the last part after split is empty.
    if endswith(strip(content), ',') && !isempty(parts_str) && isempty(strip(last(parts_str)))
        # Remove the last empty string part that resulted from a trailing comma
        pop!(parts_str) 
    end
    
    # If parts_str is now empty but content was not (e.g., content was just "," or ",,"), it's invalid.
    if isempty(parts_str) && !isempty(content)
         return nothing
    end

    elements = Any[] # Store parsed elements of potentially different types
    for part_s_individual in parts_str
        stripped_elem_str = strip(part_s_individual)
        
        # If a part (after stripping) is empty, it's an invalid format like "(1.0,,2.0)"
        if isempty(stripped_elem_str)
            return nothing 
        end
        
        parsed_value::Any = nothing
        success = false

        # Try parsing as Bool
        if stripped_elem_str == "true"
            parsed_value = true
            success = true
        elseif stripped_elem_str == "false"
            parsed_value = false
            success = true
        end

        # If not Bool, try parsing as Int
        if !success
            try
                parsed_value = parse(Int, stripped_elem_str)
                success = true
            catch e
                if !(e isa ArgumentError || e isa OverflowError) # OverflowError for too large Ints
                    rethrow(e) # Other unexpected error
                end
                # Not an Int, or too large for Int, proceed to try Float64
            end
        end

        # If not Bool or Int, try parsing as Float64
        if !success
            try
                parsed_value = parse(Float64, stripped_elem_str)
                success = true
            catch e
                if !(e isa ArgumentError)
                    rethrow(e) # Other unexpected error
                end
                # Not a Float64 either
            end
        end

        if success
            push!(elements, parsed_value)
        else
            # Element could not be parsed as Bool, Int, or Float64
            #return nothing
            push!(elements, stripped_elem_str) 
        end
    end

    return Tuple(elements)
end


"""
    assembleParams(shared_obs, method_obs_collection, method_name)

Constructs a flat parameter dictionary for a simulation run by combining
current shared parameter values and current method-specific parameter values.

Method-specific parameters override shared parameters if keys conflict.
"""
function assembleParams(
    shared_params_obs::Union{Dict{String, Observable},ParamDictType},
    method_params_collection_obs::Union{Dict{String, Dict{String, Observable}},MethodDictType},
    method_name::String
    )::ParamDictType # Assuming ParamDictType = Dict{String, Any}

    method_specific_obs_dict = haskey(method_params_collection_obs, method_name) ? method_params_collection_obs[method_name] : nothing
    # --- CORRECTED: Safely get the list of keys to ignore from the observable ---
    ignore_keys = String[] # Default to an empty list
    if haskey(method_specific_obs_dict, "ignore")
        # Get the value from the "ignore" observable
        val = to_value(method_specific_obs_dict["ignore"])
        if val isa AbstractVector{<:AbstractString}
            ignore_keys = val
        end
    end
    # Start with current values of shared parameters
    current_params = ParamDict()
    for (key, obs) in shared_params_obs
        if key in ignore_keys; continue end
        val = to_value(obs)
        if isa(val, Tuple) && length(val) == 2 && val[1] == :const
            current_params[key] = to_value(val[2])
        else
            current_params[key] = val
        end
    end

    # Get the specific observable dictionary for the requested method
    if !isnothing(method_specific_obs_dict)
        # Merge/override with current values of method-specific parameters
        for (key, obs) in method_specific_obs_dict
            val = to_value(obs)
            if isa(val, Tuple) && length(val) == 2 && val[1] == :const
                current_params[key] = to_value(val[2])
            else
                current_params[key] = val
            end
        end
    else
        # This might be expected if a method uses only shared params
        @warn "No specific parameters found for method '$method_name' in observable collection."
    end

    # Add method name itself (optional, but often useful for saving/loading)
    #current_params["method"] = method_name

    return current_params
end


function allMethodNames(config::SimulationConfig)
    return collect(keys(config.methods_dict))
end


# function load_project_from_git(
#     repo_path::String,
#     commit_hash::String,
#     main_module_path::String,
#     function_to_get_sym::Symbol
# )
#     original_pwd = pwd()
#     tmp_dir = mktempdir()
#     println("Created temporary directory for historical project: $tmp_dir")

#     absolute_repo_path = abspath(repo_path)
#     original_repo_parent_dir = dirname(absolute_repo_path)
#     dependency_name = "IPlotPDESols"
#     original_dependency_path = joinpath(dirname(original_repo_parent_dir), dependency_name)
    
#     tmp_parent_dir = dirname(tmp_dir)
#     temporary_dependency_path = joinpath(tmp_parent_dir, dependency_name)

#     try
#         println("Copying local dependency from $original_dependency_path to $temporary_dependency_path")
#         cp(original_dependency_path, temporary_dependency_path, force=true)

#         # # --- NEW: Manually add Logging to the IPlotPDESols Project.toml ---
#         # toml_path = joinpath(temporary_dependency_path, "Project.toml")
        
#         # # Load the Project.toml file
#         # project_dict = Pkg.TOML.parsefile(toml_path)
        
#         # # Add the Logging dependency with its UUID
#         # if !haskey(project_dict, "deps")
#         #     project_dict["deps"] = Dict{String, Any}()
#         # end
#         # project_dict["deps"]["Logging"] = "56ddb016-857b-54e1-b83d-db4d58db5568"
        
#         # # Save the modified Project.toml file
#         # open(toml_path, "w") do io
#         #     Pkg.TOML.print(io, project_dict)
#         # end
#         # println("Added 'Logging' to IPlotPDESols's Project.toml.")

#         println("Cloning project to temporary directory...")
#         run(`git clone $absolute_repo_path $tmp_dir`)
        
#         cd(tmp_dir)
#         run(`git checkout $commit_hash`)
        
#         # Now Pkg can see the updated IPlotPDESols dependency
#         println("Activating historical project and installing dependencies...")
#         Pkg.activate(".")
#         Pkg.resolve()
#         Pkg.instantiate()
        
#         absolute_main_module_path = joinpath(tmp_dir, main_module_path)
        
#         println("Loading historical main module from: $absolute_main_module_path")
#         include(absolute_main_module_path)
        
#         main_module_name = Symbol(splitext(basename(main_module_path))[1])
        
#         if isdefined(Main, main_module_name)
#             main_module = getfield(Main, main_module_name)
#             if isdefined(main_module, function_to_get_sym)
#                 println("Successfully loaded and sandboxed project from commit $(first(commit_hash, 7))")
#                 return getfield(main_module, function_to_get_sym)
#             else
#                 @error "Function '$function_to_get_sym' not found in historical project's main module."
#                 return nothing
#             end
#         else
#             @error "Main module '$main_module_name' not found after including the project file."
#             return nothing
#         end
        
#     catch e
#         @error "Failed to load project from Git history." exception=(e, catch_backtrace())
#         return nothing
#     finally
#         cd(original_pwd)
#         Pkg.activate(".")
#         rm(tmp_dir, recursive=true, force=true)
#         rm(temporary_dependency_path, recursive=true, force=true)
#         println("Cleaned up temporary directory.")
#     end
# end


"""
    _load_function_from_string(content::String, function_name_sym::Symbol) -> Function

Safely loads Julia code from a string into an isolated, anonymous module
and returns a handle to the specified function.
"""
function _load_function_from_string(content::String, function_name_sym::Symbol)
    # Create a sandboxed module to load the code into, preventing conflicts.
    sandbox_module = Module()
    # Evaluate the file's content within the new module's scope.
    Base.include_string(sandbox_module, content)
    
    if isdefined(sandbox_module, function_name_sym)
        return getfield(sandbox_module, function_name_sym)
    else
        @error "Function '$function_name_sym' was not found in the provided code."
        return nothing
    end
end

"""
    load_function_from_git(repo_path, commit_hash, function_name_sym) -> Function

Retrieves a specific simulation function from Git history. This version uses the
robust `Commit -> Tree -> Blob` lookup pattern.
"""
function load_function_from_git(
    repo_path::String,
    commit_hash::String,
    function_name_sym::Symbol
)
    file_in_repo = "SimulationFunctions/$(function_name_sym).jl"
    try
        repo = LibGit2.GitRepo(repo_path)
        commit = LibGit2.GitCommit(repo, commit_hash)
        
        # --- THIS IS THE FIX ---
        # 1. Get the tree object (the root directory) from the commit.
        tree = LibGit2.peel(LibGit2.GitTree, commit)
        
        # 2. Look up the file path within the tree to get the blob (the file content).
        #    The tree can be indexed like a dictionary.
        blob = tree[file_in_repo]
        
        if isnothing(blob)
            @error "File '$file_in_repo' not found in commit '$commit_hash'."
            return nothing
        end
        # --- END OF FIX ---
        
        file_content = String(LibGit2.content(blob))
        
        func = _load_function_from_string(file_content, function_name_sym)
        if !isnothing(func)
            println("Successfully loaded function '$function_name_sym' from commit $(first(commit_hash, 7))")
        end
        return func
    catch e
        @error "Failed to load '$file_in_repo' from Git commit '$commit_hash'." exception=(e, catch_backtrace())
        return nothing
    end
end

"""
    create_sim_config_from_csv(csv_filepath::String, sim_function::Function) -> SimulationConfig

Reads a "tidy" format CSV file and reconstructs a `SimulationConfig` object from it.

# Arguments
- `csv_filepath::String`: The path to the saved parameters CSV file.
- `sim_function::Function`: The handle to the simulation function to be used. This
  cannot be stored in the CSV and must be provided manually.

# Returns
- A `SimulationConfig` object populated with the data from the CSV.
"""
function create_sim_config_from_csv(
    csv_filepath::String,
    sim_function::Function
)
    # --- 1. Read and Parse the CSV ---
    if !isfile(csv_filepath)
        error("CSV file not found at: $csv_filepath")
    end
    
    df = CSV.read(csv_filepath, DataFrame)
    
    # Create a new column with correctly typed values
    df.ParsedValue = [parseValue(string(v)) for v in df.Value]

    # --- 2. Reconstruct Shared Parameters ---
    shared_params_df = filter(row -> row.Section == "Shared", df)
    shared_params = Dict{String, Any}(
        row.Parameter => row.ParsedValue for row in eachrow(shared_params_df)
    )

    # --- 3. Reconstruct Method-Specific Parameters ---
    methods_df = filter(row -> row.Section == "Method", df)
    methods_dict = Dict{String, Dict{String, Any}}()
    
    # Group the DataFrame by the "MethodName" column
    grouped_by_method = groupby(methods_df, :MethodName)
    
    for method_group in grouped_by_method
        method_name = method_group.MethodName[1]
        method_params = Dict{String, Any}(
            row.Parameter => row.ParsedValue for row in eachrow(method_group)
        )
        methods_dict[method_name] = method_params
    end

    # --- 4. Determine Default Methods ---
    # For reproducibility, we assume all methods found in the file were the "active" ones.
    default_methods = collect(keys(methods_dict))

    # --- 5. Construct and Return the SimulationConfig ---
    println("Successfully created SimulationConfig from $csv_filepath")
    return SimulationConfig(
        shared_params,
        methods_dict,
        default_methods,
        sim_function
    )
end
#======================================================================#
#              2. MAIN `create_sim_config_from_csv`
#======================================================================#

"""
    create_sim_config_from_csv(csv_filepath, time_warp; repo_path) -> SimulationConfig

Reads a "tidy" format CSV and reconstructs a `SimulationConfig` object with
varying levels of historical accuracy, controlled by the `time_warp` flag.
"""
function create_sim_config_from_csv(
    csv_filepath::String;
    time_warp::String = "none",
    repo_path::String = "." # Assumes the script is run from the repo root
)
    # --- 1. Read and Parse the CSV ---
    df = CSV.read(csv_filepath, DataFrame)
    df.ParsedValue = [parseValue(string(v)) for v in df.Value]
    context_df = filter(row -> row.Section == "Context", df)
    shared_params_df = filter(row -> row.Section == "Shared", df)
    shared_params = Dict{String, Any}(row.Parameter => row.ParsedValue for row in eachrow(shared_params_df))
    context = Dict(row.Parameter => row.ParsedValue for row in eachrow(context_df))

    # --- 2. Determine and Load the Simulation Function ---
    sim_func_name_str = get(shared_params, "sim_function", nothing)
    if isnothing(sim_func_name_str)
        error("CSV is missing required context key: 'sim_function'.")
    end
    sim_func_sym = Symbol(sim_func_name_str)
    
    local sim_function::Function

    if time_warp == "none"
        println("Time Warp: 'none'. Using the currently saved version of the simulation function.")
        sim_function = load_function_from_disk(repo_path, sim_func_sym)

    elseif time_warp == "partial"
        println("Time Warp: 'partial'. Loading historical function into current environment...")
        commit_hash = string(get(context, "git_commit_hash", nothing))
        if isnothing(commit_hash); error("CSV is missing 'git_commit_hash' for partial time warp."); end
        sim_function = load_function_from_git(repo_path, commit_hash, sim_func_sym)
    # elseif time_warp == "project" # <-- NEW OPTION
    #     println("Time Warp: 'project'. Loading historical project source code...")
    #     commit_hash = string(get(context, "git_commit_hash", nothing))
    #     # We need to know the path to your main module file to start the process
    #     main_module_file = "src/Meshfree4ScalarEq.jl" # You might make this an argument
    #     sim_function = load_project_from_git(repo_path, commit_hash, main_module_file, sim_func_sym)
    elseif time_warp == "full"
        # ... (Instructions for the user as before) ...
        error("Full time warp is a manual process. Follow the instructions above.")
    else
        error("Invalid `time_warp` option.")
    end

    if isnothing(sim_function); error("Could not load the simulation function. Cannot proceed."); end

    # --- 3. Reconstruct All Parameter Dictionaries ---
    methods_df = filter(row -> row.Section == "Method", df)
    methods_dict = Dict{String, Dict{String, Any}}()
    if !isempty(methods_df)
        grouped_by_method = groupby(methods_df, :MethodName)
        for method_group in grouped_by_method
            method_name = method_group.MethodName[1]
            methods_dict[method_name] = Dict{String, Any}(row.Parameter => row.ParsedValue for row in eachrow(method_group))
        end
    end

    default_methods = collect(keys(methods_dict))

    # --- 4. Construct and Return the SimulationConfig ---
    @info "Successfully created fully reproducible SimulationConfig from $csv_filepath"
    return SimulationConfig(sim_function, shared_params, methods_dict, default_methods)
end

function load_additional_options_from_csv(
    csv_filepath::String,
    section_name::String
)
    if !isfile(csv_filepath); error("CSV file not found at: $csv_filepath"); end
    
    df = CSV.read(csv_filepath, DataFrame)
    df.ParsedValue = [parseValue(string(v)) for v in df.Value]

# --- Iterate through the requested sections and extract each one ---
    section_df = filter(row -> row.Section == section_name, df)
    
    section_dict = Dict{String, Any}(
        row.Parameter => row.ParsedValue for row in eachrow(section_df)
    )

    @info "Successfully loaded options for section: $section_name"
    return section_dict
end

function createObsDict(dict::Dict{String,Any})
    dict_obs = Dict{String,Observable}()
    for (key,val) = dict
        dict_obs[key] = Observable(val)
    end
    return dict_obs
end

function connectObsDict!(dict::Dict{String,Observable}, ks::Vector{String}, vals::Vector{Observable})
    for (i,key) = enumerate(ks)
        connect!(dict[key],vals[i])
    end
end
end