module Utils

using ..Structs  

using SHA
using CSV, DataFrames
using JLD2, FileIO
using Base.Threads
using GLMakie

export saveSimData, calculateHash, getFileName, loadSimData, getStats, doesSimDataExist, deleteSimData, 
       getAllSimData, changeStats, set_save_path!, get_save_path, StringToTuple, calculateConvergenceData,
       assembleParams


const _SAVE_ROOT_PATH = Ref{String}(pwd())

"""
Custom error type indicating that a specific simulation data file,
matching the provided parameters, was not found.
"""
struct SimFileNotFoundError <: Exception
    message::String # Optional: To store a descriptive message
end


"""
    set_save_path!(path::String)

Sets the root directory for saving plots, data, etc., generated by this module.
Also creates 'figures' and 'data' subdirectories within the specified path if 
they don't exist. For Windows a raw string is required to correctly process 
the path.

IMPORTANT!
It's recommended to call this function once at the beginning of your main script,
s.t. all the saving and loading functions function correctly. Because of the hashing 
of the names it is preferred to set the path to a shared folder for all simulations. 
The module is designed to create  all user readable data (png, pdf, csv) from a single 
data folder.



Example: `Utils.set_save_path!(joinpath(@__DIR__, "results"))`
"""
function set_save_path!(path::String)
    abs_path = abspath(path) # Ensure absolute path
    path_ok = false

    # Ensure the main directory exists
    if !isdir(abs_path)
        @warn "Save path does not exist: $abs_path. Attempting to create..."
        try
            mkpath(abs_path)
            println("Created save directory: $abs_path")
            path_ok = true
        catch e
            @error "Failed to create save directory: $abs_path. Error: $e"
            # Decide how to proceed - maybe return false or throw error?
            # For now, we won't set the path if creation fails.
            return false 
        end
    else
        path_ok = true
    end

    if path_ok
        _SAVE_ROOT_PATH[] = abs_path # Update the path stored in the Ref
        println("Module save root path set to: $(_SAVE_ROOT_PATH[])")

        # Create standard subdirectories
        for subdir in ["figures", "data"]
            subdir_path = joinpath(_SAVE_ROOT_PATH[], subdir)
            if !isdir(subdir_path)
                try
                    mkpath(subdir_path)
                    println("Created subdirectory: $subdir_path")
                catch e
                    @error "Failed to create subdirectory: $subdir_path. Error: $e"
                    # Warn but continue, maybe saving to base path will still work
                end
            end
        end
        return true # Indicate success
    else
        return false # Indicate failure
    end
end

"""
    get_save_path()::String

Returns the currently configured root directory for saving files.
"""
function get_save_path()::String
    return _SAVE_ROOT_PATH[]
end



"""
Calculates the hash of a given params dictionary
"""
function calculateHash(params::ParamDictType)
    sorted_keys = sort(collect(keys(params)))
    sorted_vals = [params[key] for key = sorted_keys]
    stringToHash = join(map(d -> "$d", sorted_vals))
    return bytes2hex(sha256(stringToHash))
end

"""
Saves the given simulation mesh in the folder given by save_data with the hash as the filename.

CAUTION: Enabling overwrite will overwrite an existing file with the given simulation mesh!
"""
function saveSimData(sim_data::AbstractSimData; overwrite::Bool = false)
    hash = calculateHash(sim_data.params)
    save_data = get_save_path() * "/data/"
    file_name = save_data * hash *".jld2"
    counter = 0
    while true
        counter += 1
        if !isfile(file_name)
            save(file_name, "sim_data", sim_data)
            println("SimData saved to file $file_name")
            break
        else
            SimDataSaved = load(file_name)["sim_data"]
            if !(sim_data.params == SimDataSaved.params)
                println("Filename already exists! Changing hash...")
                file_name = save_data * hash * "_$counter.jld2"
            else
                if overwrite
                    save(file_name, "sim_data", sim_data)
                    @warn "Simulation mesh has been overwritten!"
                    println("SimData saved to file $file_name")
                else
                    println("File already exists!")
                end
                break
            end 
        end
    end
end

"""
Returns the filename of the simulation data corresponding to the given params dictionary.
Throws SimFileNotFoundError if no matching file is found.
"""
function getFileName(params::ParamDictType)
    local file_name # Ensure file_name is scoped correctly
    hash_val = calculateHash(params) # Renamed from 'hash' to avoid conflict
    save_data = get_save_path() * "/data/"
    base_file_part = save_data * hash_val
    file = base_file_part * ".jld2"
    counter = 0

    while true
        # Construct current filename to check
        if counter == 0
            file_name = hash_val # Assign base name
        else
            file_name = hash_val * "_$(counter-1)" # Use counter-1 for _0, _1, ...
            file = save_data * file_name * ".jld2"
        end

        if isfile(file)
            try # Add inner try-catch for loading/comparison errors
                sim_data_saved = load(file)["sim_data"]
                if (params == sim_data_saved.params)
                    println("Found matching file: ", file) # Debug print
                    return file # Return the full path
                else
                    # Hash collision, prepare to check next file in the next iteration
                    println("Hash collision detected for: ", file) # Debug print
                    counter += 1
                    # Continue to the next iteration of the while loop
                end
            catch load_err
                 # Error during loading or comparison, treat as if file doesn't match
                 @warn "Error processing potential match file '$file'. Skipping." exception=(load_err, catch_backtrace())
                 counter += 1 # Prepare to check next file
            end
        else
            # If we checked the base file (counter=0) and it wasn't there, OR
            # if we checked a collision file (_N) and it wasn't there,
            # then no matching file exists with this base hash.
            println("File not found: ", file, ". Stopping search for this hash.") # Debug print
            throw(SimFileNotFoundError("Requested File does not exist! (Checked up to collision $counter)"))
            # The loop terminates here by throwing the error
        end

        # Optional: Add a safety break to prevent infinite loops in unexpected scenarios
        if counter > 100 # Or some other reasonable limit
             @warn "Exceeded collision check limit for hash $hash_val. Assuming file not found."
             throw(SimFileNotFoundError("Exceeded collision check limit for hash $hash_val."))
        end
    end
end

"""
Loads the simulation data corresponding to the given params dictionary as a simulation mesh
"""
function loadSimData(params::ParamDictType)
    return load(getFileName(params))["sim_data"]
end
function loadSimData(hash::String)
    save_data = get_save_path() * "/data/"
    file_name = save_data * hash *".jld2"
    return load(file_name)["sim_data"]
end

"""
Loads only the stats field of the simulation mesh
"""
function getStats(params::ParamDictType)
    sim_data = loadSimData(params)
    return sim_data.stats
end

"""
Checks if simulation data already exists for the given parameter dictionary.
Returns true if found, false only if specifically not found (SimFileNotFoundError).
Other errors during check will propagate.
"""
function doesSimDataExist(params::ParamDictType)
    try
        getFileName(params) # Call the function that might throw
        # If getFileName returns successfully, it means a matching file was found
        return true
    catch e
        #e = nothing
        if isa(e, SimFileNotFoundError)
            # This is the specific error indicating the file wasn't found.
            # This is NOT a bug, it's the expected outcome when data doesn't exist.
             # println("Debug (doesSimDataExist): Caught expected SimFileNotFoundError: ", e.message) # Optional
            return false # File not found, return false as intended
        else
            # This is some other, unexpected error (e.g., in calculateHash, get_save_path,
            # permissions, JLD2 issues, logic errors in getFileName).
            # We DON'T want to mask this!
            @error "Unexpected error during file existence check!" exception=(e, catch_backtrace())
            rethrow(e) # Re-throw the unexpected error to halt and allow debugging
        end
    end
end

"""
Deletes all saved simulation meshes with the given keys and values in its paramseter dictionary.
"""
function deleteSimData(keys::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        deletion = true
        for (i,key) = enumerate(keys)
            deletion = deletion && (sim_data.params[key] == vals[i]) && (sim_data.params[key] isa typeof(vals[i]))
        end
        if deletion
            @warn "Saved data at $file is being deleted!"
            rm(save_data * file)
        end
    end
end

"""
Changes the paramseter dictionary of a simulation mesh from the old values to the new ones. Helpful if unused paramseters need to be changed or the type 
is wrong (e.g. Int instead of Float). Note that the values are not changed, hence use with caution.

"""
function changeparams(ks::Vector{String}, oldVals::Vector, newVals::Vector)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                if sim_data.params[key] == oldVals[i]
                    sim_data.params[key] = newVals[i]
                    saveSimData(sim_data; overwrite = true)
                    println("Changed simulation mesh is saved!")
                end
            end
        end
    end
end

"""
Returns all saved simulation meshes with the given paramseters.
"""
function getAllSimData(ks::Vector{String}, vals::Vector)
    save_data = get_save_path() * "/data/"
    res = []
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        hit = true
        for (i,key) = enumerate(ks)
            if (key in keys(sim_data.params))
                hit = hit & (sim_data.params[key] == vals[i])
            else
                hit = false
            end
        end
        if hit
            push!(res, sim_data)
        end
    end
    return res
end

"""
Changes the given stat of all simulation meshes using the given function f. The function has to be of the
form f(u,x) or f(u,x,t) for the static and dynamic case respectively. It can also be used to add a new stat
to the simulation meshes.
"""
function changeStats(statsName::String, f::Function, simulation::String)
    save_data = get_save_path() * "/data/"
    files = readdir(save_data)
    for file = files
        sim_data = load(save_data * file)["sim_data"]
        if sim_data.params["simulation"] == simulation
            if simulation == "PDE"
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x, sim_data.t)
            else
                sim_data.stats[statsName] = f(sim_data.u, sim_data.x)
            end
            saveSimData(sim_data; overwrite = true)
        end
    end    
end

"""
    string_to_typed_tuple(s::String)::Union{Tuple, Nothing}

Attempts to parse a string representation of a tuple containing elements
that can be interpreted as Bool, Int, or Float64 into a Julia `Tuple`.
The types of the elements in the output tuple will reflect the parsed values
(e.g., could be Tuple{Float64, Bool, Int64}).

The string should be in a format like "(1.0, true, -3)".
It handles:
- Leading/trailing whitespace around the string itself.
- Whitespace around numbers, booleans, and commas within the parentheses.
- Empty tuple "()".
- Single-element tuples like "(1.23)", "(true,)", or "(1, )".
- Multiple elements like "(1.0, false, 2)".

Returns the parsed tuple (e.g., `(1.0, true, -3)`) if successful,
or `nothing` if the string is not in the expected format or if any
element cannot be parsed as Bool, Int, or Float64.

# Examples
```jldoctest
julia> string_to_typed_tuple("(1.0, true, -3)")
(1.0, true, -3)

julia> string_to_typed_tuple("( 42,  false )")
(42, false)

julia> string_to_typed_tuple("(3.14,)")
(3.14,)

julia> string_to_typed_tuple("()")
()

julia> string_to_typed_tuple("not a tuple") # returns nothing

julia> string_to_typed_tuple("(1, abc, 3)") # returns nothing

julia> string_to_typed_tuple("(1.0, , 2.0)") # returns nothing
```
"""
function StringToTuple(s::String)::Union{Tuple, Nothing}
    # Strip leading/trailing whitespace from the whole string
    s_stripped = strip(s)

    if s_stripped == "()" return () end

    # Check for enclosing parentheses
    if !startswith(s_stripped, "(") || !endswith(s_stripped, ")")
        return nothing
    end

    # Extract content within parentheses
    if length(s_stripped) < 2 # Should only be true for malformed like "("
        return nothing
    end
    content = s_stripped[begin+1:end-1]
    
    # Handle empty tuple case like "()" -> content is ""
    if isempty(strip(content))
        return () # Return an empty tuple of type Tuple{}
    end

    # Split by comma
    parts_str = split(content, ',')
    
    # Handle potential empty string from a trailing comma before the closing parenthesis
    # e.g., content "1.0," or "1.0, 2.0,"
    # A robust way to check for trailing comma: if the original content (after stripping outer parens)
    # ended with a comma, and the last part after split is empty.
    if endswith(strip(content), ',') && !isempty(parts_str) && isempty(strip(last(parts_str)))
        # Remove the last empty string part that resulted from a trailing comma
        pop!(parts_str) 
    end
    
    # If parts_str is now empty but content was not (e.g., content was just "," or ",,"), it's invalid.
    if isempty(parts_str) && !isempty(content)
         return nothing
    end

    elements = Any[] # Store parsed elements of potentially different types
    for part_s_individual in parts_str
        stripped_elem_str = strip(part_s_individual)
        
        # If a part (after stripping) is empty, it's an invalid format like "(1.0,,2.0)"
        if isempty(stripped_elem_str)
            return nothing 
        end
        
        parsed_value::Any = nothing
        success = false

        # Try parsing as Bool
        if stripped_elem_str == "true"
            parsed_value = true
            success = true
        elseif stripped_elem_str == "false"
            parsed_value = false
            success = true
        end

        # If not Bool, try parsing as Int
        if !success
            try
                parsed_value = parse(Int, stripped_elem_str)
                success = true
            catch e
                if !(e isa ArgumentError || e isa OverflowError) # OverflowError for too large Ints
                    rethrow(e) # Other unexpected error
                end
                # Not an Int, or too large for Int, proceed to try Float64
            end
        end

        # If not Bool or Int, try parsing as Float64
        if !success
            try
                parsed_value = parse(Float64, stripped_elem_str)
                success = true
            catch e
                if !(e isa ArgumentError)
                    rethrow(e) # Other unexpected error
                end
                # Not a Float64 either
            end
        end

        if success
            push!(elements, parsed_value)
        else
            # Element could not be parsed as Bool, Int, or Float64
            return nothing 
        end
    end

    return Tuple(elements)
end


"""
    assembleParams(shared_obs, method_obs_collection, method_name)

Constructs a flat parameter dictionary for a simulation run by combining
current shared parameter values and current method-specific parameter values.

Method-specific parameters override shared parameters if keys conflict.
"""
function assembleParams(
    shared_params_obs::Union{Dict{String, Observable},ParamDictType},
    method_params_collection_obs::Union{Dict{String, Dict{String, Observable}},MethodDictType},
    method_name::String
    )::ParamDictType # Assuming ParamDictType = Dict{String, Any}

    # Start with current values of shared parameters
    current_params = ParamDict()
    for (key, obs) in shared_params_obs
        val = to_value(obs)
        if isa(val, Tuple) && length(val) == 2 && val[1] == :const
            current_params[key] = to_value(val[2])
        else
            current_params[key] = val
        end
    end

    # Get the specific observable dictionary for the requested method
    if haskey(method_params_collection_obs, method_name)
        method_specific_obs_dict = method_params_collection_obs[method_name]
        # Merge/override with current values of method-specific parameters
        for (key, obs) in method_specific_obs_dict
            val = to_value(obs)
            if isa(val, Tuple) && length(val) == 2 && val[1] == :const
                current_params[key] = to_value(val[2])
            else
                current_params[key] = val
            end
        end
    else
        # This might be expected if a method uses only shared params
        @warn "No specific parameters found for method '$method_name' in observable collection."
    end

    # Add method name itself (optional, but often useful for saving/loading)
    #current_params["method"] = method_name

    return current_params
end
"""
    calculateConvergenceData(sim_config::SimulationConfig,
                             key_varied::String,
                             param_values_for_key::Union{AbstractVector, AbstractRange};
                             force_int_param::Bool = false)

Runs simulations for each method in `sim_config` across each value in
`param_values_for_key` (for the `key_varied`) IN PARALLEL.
Returns a dictionary of results.
"""
function calculateConvergenceData(
    sim_config::SimulationConfig,
    key_varied::String, # The parameter key being varied (e.g., "N", "CFL")
    param_values_for_key::Union{AbstractVector, AbstractRange};
    force_int_param::Bool = false,
    force_overwrite::Bool = false
)

    all_method_labels = collect(keys(sim_config.methods_dict)) # These are the UI labels
    num_methods = length(all_method_labels)
    num_p_values = length(param_values_for_key)

    # --- Prepare a list of all individual simulation tasks (parameter dictionaries) ---
    # Each task is a fully specified ParamDictType ready for the sim_function
    num_tasks = num_methods * num_p_values
    tasks_params_list = Vector{ParamDictType}(undef, num_tasks)
    # Store identifiers to map results back correctly
    task_identifiers = Vector{Tuple{String, Int}}(undef, num_tasks) # (method_label, param_value_index)

    task_idx = 0
    for method_label in all_method_labels
        # Get base parameters for this method label: shared + method_specific_overrides
        # This replicates the logic from your IPlotPDESols.assemble_params_for_run
        # but uses direct values instead of observables.
        current_method_base_params = assembleParams(sim_config.shared_params, sim_config.methods_dict,method_label)

        for (j, p_val) in enumerate(param_values_for_key)
            task_idx += 1
            # Create a specific param dict for this run
            params_for_this_run = copy(current_method_base_params)
            # Set the varied parameter
            params_for_this_run[key_varied] = force_int_param ? trunc(Int64, p_val) : p_val

            # The sim_function (e.g., runBurgersSimulation_for_IPlotPDESols)
            # will use component keys like "timestepper", "main_gradient" etc.
            # already present in params_for_this_run from the merge above.

            tasks_params_list[task_idx] = params_for_this_run
            task_identifiers[task_idx] = (method_label, j)
        end
    end
    # ------------------------------------------------------------------------

    println("Starting parallel calculation of $(num_tasks) convergence simulations...")
    # --- Parallel Execution ---
    # WARNING: The effectiveness and correctness of RNG handling inside
    # runSimulation_for_IPlotPDESols when called in parallel like this needs
    # careful consideration. If it modifies a shared global RNG, there could be issues.
    Threads.@threads for i in 1:num_tasks
        params_for_this_run = tasks_params_list[i]
        method_label_this_run, p_val_idx = task_identifiers[i]
        p_val_actual = param_values_for_key[p_val_idx]

        println("Thread $(Threads.threadid()): Starting Sim - Label: '$method_label_this_run', $key_varied = $p_val_actual")

        # Call the sim_function (e.g., runBurgersSimulation_for_IPlotPDESols)
        # It should return only the SimData object or nothing
        if !doesSimDataExist(params_for_this_run) || force_overwrite
            sim_data = sim_config.sim_function(params_for_this_run)
        else
            sim_data = "skipped"
            @info "Skipped calculation because existing simulation data was found. If recalculation is wanted, enable force_overwrite!"
        end
        if isnothing(sim_data)
            @warn "Simulation could not run correctly for the method $method_label_this_run and $key_varied = $p_val_actual"
        elseif !(sim_data == "skipped")
            saveSimData(sim_data; overwrite = force_overwrite)
        end
        println("Thread $(Threads.threadid()): Finished Sim - Label: '$method_label_this_run', $key_varied = $p_val_actual")
    end

    println("Convergence data calculation complete.")
end

end